假日/n 特/ag 享/vg ，/wd 德克士/nrf 咔/o 滋/v 咔/o 滋/vg 乐/ng 响/v 国庆/t ——/wp 德克士/nrf 首/m 度/qv 推出/v 超/h 值/n 国庆/t 大/d 排/v 桶/n   
    (/wkz 2012/m ，/wd 中国/ns ，/wd 上海/ns )/wky  知名/a 快餐/n 连锁/vn 品牌/n 德/n 克/vg 士/ng 中秋/t 十一/m 长假/n 重磅/n 推出/v 超/h 值/n 桶/q 餐/ng -/wp “/wyz 国庆/t 大/d 排/v 桶/n ”/wyy 。/wj 2012年/t 9月/t 30日/t 至/p 10月/t 7日/t 中秋/t 、/wn 国庆/t 假期/t 期间/f ，/wd 德克士/nrf 首/m 次/qv 推出/v 售价/n 75/m 元/q 的/ude1 3/m 人/n 份/q 超/h 值/n 经/p 实惠/an 组合/vn 套餐/n ，/wd 此/rzs 套餐/n 中/f ，/wd 不仅/c 含有/v 德/n 克/vg 士/ng 经典/n 美味/n 脆/a 皮/n 炸鸡/n 、/wn 双/m 鸡/n 汉堡/nsf 和/cc 香/a 辣/a 鸡翅/n 和/cc 百事可乐/nz ，/wd 还/d 给/p 力/n 搭配/vn 新品/n “/wyz 脆/a 皮/n 鸡/n 排/v ”/wyy 。/wj 假日/n 特/ag 享/vg ，/wd 德克士/nrf 经典/n 美味/n 一网打尽/vl ，/wd “/wyz 鸡/n ”/wyy 不可/v 失/v 。/wj 
    史/ng 上/f 最/d 长/a 假期/t 带动/v 全国/n 出游/vn 聚会/vn 热潮/n 
    中秋/t 国庆/t 黄金/n 周/qt ，/wd 史/ng 上/f 最/d 长/a 假期/t 带动/v 全国/n 出游/vn 聚会/vn 热潮/n 。/wj 炸鸡/n 专家/n 德克士/nrf 特别/d 推出/v 国庆/t 乐/ng 享/vg 超/v 值/n 大/d 排/v 桶/q ，/wd 可/v 供/vi 3/m 人/n 同/p 享/vg ，/wd 成为/v 黄金/n 周/nr1 欢庆/v 聚会/vi 出游/v 唱/v K/x 标/ng 配/v 桶/n 餐/ng ！/wt 9月/t 30日/t 至/p 10月/t 7日/t 八日/t 假期/t ，/wd 日日/d 超/v 值/v 欢乐/a 享/vg 。/wj 长假/n 出游/vn ，/wd 遍布/v 全国/n 475/m 个/q 城市/n 的/ude1 1200/m 多/m 家/q 德克士/nrf 门店/n ，/wd 所/usuo 到/v 美景/n 之/uzhi 处/n 均/d 有/vyou 德/n 克/vg 士/ng 相伴/vi ，/wd 旅途/n 中/f 也/d 不怕/v 错过/v 尽情/d 享受/v 节日/n 特/ag 供/vi 的/ude1 机会/n 。/wj 脆/a 皮/n 炸鸡/n 、/wn 双/m 鸡/n 堡/ng 、/wn 香/a 辣/a 鸡翅/n ，/wd 等/udeng 多/m 款/q 经典/n 人气/n 产品/n 搭配/vn 饮料/n ，/wd 更/d 有/vyou 脆/a 皮/n 家族/n 新/a 成员/n 脆/a 皮/n 鸡/n 排/v ，/wd 品种/n 丰富/a ，/wd 美味/n 一/m 桶/q 尽/vi 享/vg ，/wd 让/v 你/rr 咔/o 滋/v 咔/o 滋/v 过/uguo 足/a 瘾/n ，/wd 与/p 朋友/n 家人/n 旅伴/n 相约/v 德/n 克/vg 士/ng ，/wd 享受/v 超长/b 假期/t ，/wd 更/d 能/v 享受/v 分享/v 美味/n 的/ude1 乐趣/n 。/wj  
年轻人/n 相约/v 德/n 克/vg 士/ng 畅/a 享/vg 国庆/t 大/d 排/v 桶/n  
    德克士/nrf 脆/a 皮/n 炸鸡/n 家族/n 又/d 添/v 新/a 成员/n 
    炸鸡/n 专家/n 德克士/nrf 依靠/v 独家/b 秘/b 制/v 工艺/n ，/wd 以/p 其/rz 独特/a 的/ude1 香/a 脆/a 多/m 汁/ng 、/wn 咔/o 滋/v 咔/o 滋/v 的/ude1 口感/n 闻名/v 全国/n 。/wj 德克士/nrf 脆/a 皮/n 系列/n 一直/d 广/ad 受/v 消费者/n 的/ude1 欢迎/vn 。/wj 继/vg 鸡/n 排/v 大亨/n 之后/f ，/wd 2012年/t 中秋/t 国庆/t 前夕/f ，/wd 由/p 全球/n 华人/n 巨星/n 罗/nr1 志/n 祥/ag 激情/n 演绎/v 的/ude1 德克士/nrf “/wyz 脆/a 皮/n 鸡/n 排/v ”/wyy 电视/n 广告/n 陆续/d 登陆/vi 中国/ns 各/rz 大/a 电视/n 媒体/n ，/wd 标志/v 德/n 克/vg 士/ng 脆/a 皮/n 炸鸡/n 家族/n 新/a 成员/n “/wyz 脆/a 皮/n 鸡/n 排/v ”/wyy 正式/ad 上市/vi 。/wj “/wyz 脆/a 皮/n 鸡/n 排/v ”/wyy 不仅/c 延续/v 了/ule 鸡/n 排/v 大亨/n 的/ude1 美味/n 配方/n 与/cc 脆/a 皮/n ，/wd 此次/rz 贴心/a 定位/n 为/p 单人/b 食用/vn 份量/nz ，/wd 鲜嫩/a 多/m 汁/ng 的/ude1 无/v 骨/ng 鸡肉/n 配合/v 美妙/a 经典/n 佐料/n ，/wd 纯/a 肉/n 更/d 过瘾/a ，/wd 超高/b 性/n 价/n 比/v ，/wd 单独/b 售价/n 12/m 元/q ，/wd 配合/v 套餐/n 加/v 点/qt 只/d 需/v 8/m 元/q ！/wt   
 德克士/nrf 店员/n 热情/ad 向/p 情侣/n 推荐/v 脆/a 皮/n 炸鸡/n 套餐/n   
    关于/p 德克士/nrf 和/cc 顶/v 新/a 集团/n 
    德克士/nrf 是/vshi 顶/v 新/a 集团/n 下/f 的/ude1 餐饮/n 品牌/n ，/wd 顶/v 新/a 国际/n 集团/n 自/p 1988年/t 开始/v 投资/vn 大陆/n ，/wd 经过/p 二十三/m 年/qt 发展/vn ，/wd 拥有/v 了/ule 闻名/v 的/ude1 康师傅/nz 等/udeng 品牌/n ，/wd 集团/n 旗/n 下/f 主要/d 有/vyou 食品/n 制造业/n 康师傅/nz 和/cc 味/ng 全/a 、/wn 流通/vn 事业/n 有/vyou 全家/n 便利/an 店/n 、/wn 餐饮/n 连锁/vn 事业/n 有/vyou 德克士/nrf 和/cc 康师傅/nz 私房/n 牛肉面/n 等/udeng 三/m 大/a 投资/vn 事业/n 。/wj 近年来/dl 德/n 克/vg 士/ng 推出/v 如/v 鸡/n 排/v 大亨/n 、/wn 脆/a 皮/n 手枪/n 腿/n 、/wn 脆/a 皮/n 照/vd 烧/vi 饭/n 等/udeng 产品/n 都/d 深受/v 各地/rzs 消费者/n 的/ude1 喜爱/vn ，/wd 而/cc 英雄/n 产品/n -/wp 德克士/nrf 脆/a 皮/n 炸鸡/n 也/d 是/vshi 最/d 符合/v 国/n 人/n 喜爱/v 的/ude1 炸鸡/n 口味/n 。/wj 截至/v 目前/t ，/wd 德克士/nrf 在/p 全国/n 各地/rzs 已/d 超过/v 1/m ,/wd 200/m 家/q 门/n 店/n ，/wd 用心/ad 提供/v 美味/n 食品/n 与/cc 亲切/a 服务/vn ，/wd 更/d 有/vyou 精选/v 秘/ng 制/v 配方/n 腌/v 渍/ng 入味/v 精心/ad 烹/v 炸/v 的/ude1 脆/a 皮/n 炸鸡/n ，/wd 以及/cc 其他/rzv 多/m 款/q 汉堡/nsf 小/a 食/ng 以及/cc 缤纷/z 夏日/n 冰/n 品/ng ，/wd 无论/c 何时/ryt 何/ry 地/n 都/d 令/v 人/n 食指/n 大/d 动/v 。/wj  