昨天/t 上午/t ，/wd 中国/ns 首/m 艘/q 航空母舰/n “/wyz 辽宁/ns 舰/ng ”/wyy 正式/ad 交接/vi 入列/v 。/wj 自/p 去年/t 七月份/t 国防部/n 宣布/v 正/d 在/p 改造/v 一/m 艘/q 废旧/b 航母/n 以来/f ，/wd 已/d 有/vyou 一/m 年/qt 多/m 时间/n 。/wj 这/rzv 期间/f ，/wd 中国/ns 航母/n 平台/n 进行/vx 了/ule 多次/mq 海/n 试/v ，/wd 按照/p 既定/b 计划/n 开展/v 各项/r 科研/n 试验/vn ，/wd 实现/v 了/ule 既定/b 目标/n 。/wj “/wyz 辽宁/ns 舰/ng ”/wyy 是/vshi 中国/ns 的/ude1 第一/m 艘/q 航母/n ，/wd 也/d 是/vshi 中国/ns 海军/n 走向/v 远洋/b 的/ude1 起点/n 。/wj 

从/p 世界/n 上/f 第一/m 艘/q 现代/t 航母/n ——/wp 1918年/t 9月/t 入列/v 的/ude1 英国/ns 皇家/n 海军/n “/wyz 百/m 眼/q 巨人/n ”/wyy 号/n 算/v 起/vf ，/wd 迄今/d 已/d 有/vyou 近/a 百年/mq 的/ude1 时间/n 。/wj 在/p 这/rzv 将/d 近/a 一个/mq 世纪/n 的/ude1 沧海桑田/vl 中/f ，/wd 中国/ns “/wyz 航母/n 梦/n ”/wyy 一直/d 未曾/d 中断/v 。/wj 从/p 北洋/b 时期/n 主张/v 修建/v 航母/n 的/ude1 陈绍宽/nr 到/v 要/v 为/p 建造/v 航母/n 捐/v 压岁钱/n 的/ude1 小学生/n ，/wd 从/p 甲午/t 海战/v 之/uzhi 殇/vg 到/v “/wyz 蓝/a 水/n 海军/n ”/wyy 之/uzhi 梦/n …/ws …/ws “/wyz 辽宁/ns 舰/ng ”/wyy 承载/v 了/ule 太/d 多/a 历史/n 与/cc 时代/n 的/ude1 期盼/vn 。/wj 

中国/ns 需要/v “/wyz 辽宁/ns 舰/ng ”/wyy 。/wj 航空母舰/n 是/vshi 目前/t 人类/n 所/usuo 掌握/v 与/cc 使用/v 的/ude1 最/d 先进/a 海上/s 军事/n 平台/n ，/wd 被/pbei 视作/v 一个/mq 国家/n 综合国力/nl 和/cc 海军/n 实力/n 的/ude1 象征/n 。/wj 一方面/c 是/vshi 目前/t 世界/n 上/f 共/d 有/vyou 美/b 、/wn 英/b 、/wn 法/n 、/wn 俄/b 等/udeng 9/m 个/q 国家/n 拥有/v 航母/n ，/wd 在/p 联合国安理会/nt 5/m 个/q 常任/b 理事国/n 中/f ，/wd 此前/t ，/wd 中国/ns 是/vshi 唯一/d 没有/v 航母/n 的/ude1 国家/n ；/wf 另一方面/c 是/vshi 中国/ns 拥有/v 1.8万/m 多/m 公里/q 海岸线/n 和/cc 300万/m 平方公里/q 海洋/n 国土/n 。/wj 从/p 1840年/t 鸦片战争/nz 到/v 1949年/t 新/a 中国/ns 成立/vi ，/wd 中华民族/n 遭受/v 来自/v 海上/s 的/ude1 外国/n 侵略/vn 达/v 470/m 余/m 次/qv 。/wj “/wyz 辽宁/ns 舰/ng ”/wyy 的/ude1 问世/vn ，/wd 是/vshi 中国/ns 战略/n 的/ude1 应有/v 之/uzhi 义/ng 。/wj 

中国/ns 人/n 需要/v “/wyz 辽宁/ns 舰/ng ”/wyy 。/wj 在/p 今年/t 的/ude1 全国/n 两会/n 上/f ，/wd 几乎/d 所有/b 解放军/n 代表/n 、/wn 委员/n 都/d 被/pbei 媒体/n 问及/v 有关/p 中国/ns 航母/n 的/ude1 问题/n ；/wf 而/cc 更/d 早/a 些/q 时候/n ，/wd 有关/p 中国/ns 航母/n 计划/n 的/ude1 猜想/vn 已/d 成/v 热点/n ，/wd 一些/mq 网友/n 设计/vn 、/wn 制作/v 的/ude1 航母/n 猜想/vn 图/n 也/d 开始/v 在/p 网络/n 上/f 亮相/vi 。/wj 与其说/c “/wyz 航母/n 情结/n ”/wyy 是/vshi 一/m 种/q 诉诸/v 器物/n 的/ude1 “/wyz 大国/n 情结/n ”/wyy ，/wd 倒不如/v 说/v ，/wd 今天/t 的/ude1 中国/ns 人/n 在/p 复杂/a 的/ude1 国际/n 局势/n 中/f 更/d 好/a 地/ude2 理解/v 了/ule “/wyz 和平/n ”/wyy 二/m 字/n ：/wp 和平/n ，/wd 首先/d 是/vshi 一/m 种/q 能力/n ，/wd 然后/c 才/d 是/vshi 一/m 种/q 价值/n 诉/vg 求/v 。/wj 

中国/ns 海军/n 需要/v “/wyz 辽宁/ns 舰/ng ”/wyy 。/wj 无论是/c 海上/s 联合/vn 作战/vn 能力/n ，/wd 还/d 是/vshi 海上/s 防卫/vn 作战/vn 能力/n ，/wd 离开/v 武器/n 装备/n 体系/n 的/ude1 完善/vn 与/cc 优化/vn ，/wd “/wyz 和谐/a 海洋/n ”/wyy 就/d 有/vyou 沦为/v 空谈/v 的/ude1 危险/an 。/wj “/wyz 辽宁/ns 舰/ng ”/wyy 的/ude1 意义/n ，/wd 在于/v 增强/v 了/ule 中国/ns 海军/n 远/a 海/n 合作/vn 与/cc 应对/v 非传统/b 安全/an 威胁/vn 的/ude1 能力/n ，/wd 为/p 中国/ns 崛起/v 提供/v 海上/s 安全/an 保障/vn 。/wj 

天下/n 虽/c 安/v ，/wd 忘/v 战必危/nr 。/wj “/wyz 瓦/n 良/ag 格/ng 号/n ”/wyy 的/ude1 涅/vg 槃/n 重/d 生/v ，/wd 是/vshi 中国/ns 航母/n 的/ude1 关键性/n 一/m 步/qv 。/wj 尽管/c 这/rzv 步伐/n 未必/d 那么/rz 轻盈/a 稳健/a ，/wd 也/d 尽管/c 还有/v 更/d 远/a 的/ude1 路/n 要/v 走/v ，/wd 但/c “/wyz 辽宁/ns 舰/ng ”/wyy 已经/d 掀开/v 了/ule 一个/mq 纪元/n ——/wp 中国/ns 航母/n ，/wd 将/d 从/p 这里/rzs 起航/vi 。/wj 
