中共/n 还有/v 政/ng 改/v 的/ude1 可能性/n 吗/y ？/ww 中共/n 不/d 知道/v 政/ng 改/v 是/vshi 自己/rr 的/ude1 命/n 门/n  

中共/n 还有/v 政/ng 改/v 的/ude1 可能性/n 吗/y ？/ww 

杨光/nr 

中共/n 不/d 知道/v 政/ng 改/v 是/vshi 自己/rr 的/ude1 命/n 门/n 

中共/n 是否/v 会/v 政/ng 改/v ？/ww 何时/ryt 会/v 政/ng 改/v ？/ww 会/v 怎样/ryv 政/ng 改/v ？/ww 这/rzv 是/vshi 一九七八年/t 以来/f 中国/ns 最/d 大/a 的/ude1 政治/n 悬念/n 。/wj 人们/n 普遍/ad 认/v 為/n ，/wd 政治/n 改革/vn 是/vshi 一个/mq 充/v  满/v 了/ule 机遇/n 与/cc 创新/vi 的/ude1 高度/n 不/d 确定/v 的/ude1 领域/n ，/wd 将/d 会/v 比/p 经济/n 改革/vn 具有/v 更/d 多/a 的/ude1 变数/n 、/wn 呈现/v 更加/d 丰富多彩/vl 的/ude1 可能性/n 。/wj 这些/rz 变数/n 与/cc 可能性/n 一旦/d 展开/v ，/wd 必将/d 為/n 中国/ns 的/ude1 未来/t 提供/v 更/d 大/a 的/ude1 发/v  展/vg 空间/n 和/cc 更/d 多/a 的/ude1 选择/vn 余地/n 。/wj 人们/n 也/d 普遍/ad 认/v 為/n ，/wd 如果/c 中共/n 始终/d 推/v 搪/v 永不/d 政/ng 改/v ，/wd 这/rzv 将/d 是/vshi 所有/b 选择/vn 中/f 最/d 坏/a 的/ude1 选择/vn 。/wj 因/p 為/n 每/rz 拖延/v 政/ng 改/v 一/m 天/qt ，/wd 中共/n 的/ude1 劣质/b 官僚/n 系统/n 就/d 将/d 在/p 堕落/vi 、/wn  腐朽/a 、/wn 糜烂/vi 的/ude1 粪坑/n 里/f 更/d 深陷/v 一/m 天/qt ；/wf 而/cc 那些/rz 极端/n 主义/n 的/ude1 、/wn 破坏性/n 的/ude1 政治/n 势力/n 如/v 民粹主义/n 、/wn 极端/n 民族主义/n 、/wn 地方/n 分离/vn 主义/n 、/wn 军人/n 政客/n 集团/n 、/wn 血统/n 主义/n 的/ude1 「/n 太子/n 党/n 」/n 等/udeng  等/v 就/d 将/d 获得/v 更/d 多/a 一/m 天/qt 的/ude1 政治/n 滋养/v ，/wd 中国/ns 的/ude1 前景/n 也/d 就/d 将/d 更加/d 风险/n 莫/d 测/v 、/wn 阴郁/a 黯淡/an 。/wj 

在/p 权贵/n 主导/n 的/ude1 经济/n 改革/vn 逐渐/d 失去/v 社会/n 支持/v 的/ude1 情形/n 下/f ，/wd 正是/v 对/p 政治/n 改革/vn 的/ude1 想象/vn 和/cc 预期/vn ，/wd 构成/v 了/ule 中共/n 政权/n 继续/v 存在/v 下去/vf 的/ude1 主要/b 民/ng  意/b 基础/n ./wj 如果/c 人们/n 预感/v 到/v 中共/n 的/ude1 政治/n 改革/vn 将/d 永远/d 也/d 不/d 会/v 到来/vi ，/wd 或者/c ，/wd 如果/c 人们/n 解/v 到/v 中共/n 的/ude1 主动/a 政/ng 改/v 将/d 完全/ad 不/d 可能/v 满足/v 民/ng 眾/n 的/ude1 想象/vn 和/cc 预期/vn ，/wd 那么/c ，/wd 绝大多数/m 中国/ns 人/n 将/d  会/v 逐渐/d 撤销/v 对/p 中共/n 政权/n 的/ude1 期待/vn 与/cc 支持/vn 。/wj 以/p 此/rzs 而/cc 论/v ，/wd 政治/n 改革/vn 实/ad 乃/v 中共/n 的/ude1 命/n 门/n ，/wd 但/c 中共/n 当局/n 似乎/d 并/d 未/d 意识/vi 到/v 这/rzv 一点./t 

应该/v 说/v ，/wd 中共/n 政/ng 改/v 的/ude1 基本/a 前提/n 是/vshi 早就/d 具备/v 了/ule 的/ude1 。/wj 这个/rz 前提/n 就/d 是/vshi ：/wp 中国/ns 需要/v 政/ng 改/v ，/wd 民/ng 眾/n 盼望/v 政/ng 改/v ，/wd 时代/n 呼唤/v 政/ng 改/v 。/wj 而且/c ，/wd 几乎/d  所有/b 的/ude1 人/n 包括/v 中共/n 权贵/n 自己/rr 都/d 知道/v ：/wp 不/d 政/ng 改/v 是/vshi 死路一条/nl ./wj 在/p 这个/rz 已经/d 严重/ad 分化/vi 的/ude1 社会/n 里/f ，/wd 左/f 与/p 右/f 、/wn 富/vg 与/p 贫/ag 、/wn 朝/tg 与/p 野/ng ，/wd 不管/c 他们/rr 在/p 其他/rzv 问题/n 上/f 有/vyou 多么/d 大/a 的/ude1 分/n  歧/ag ，/wd 但/c 大家/rr 有/vyou 著/vg 一个/mq 共同/b 的/ude1 认知/vn ，/wd 那/rzv 就/d 是/vshi ：/wp 中共/n 专制/n 政体/n 绝不/d 可能/v 长久/ad 维持/v 下去/vf ，/wd 它/rr 非/b 改/v 不可/v ，/wd 非/b 大/a 改/vd 不可/v 。/wj 即使/c 是/vshi 中共/n 高层/n 里/f 那/rzv 一小撮/mq 最/d 顢/n 頇/n 、/wn 最/d 顽固/a 的/ude1 人/n ，/wd 恐怕/d  也/d 不/d 至/p 於/nr1 真/d 就/d 愚蠢/a 到/v 了/ule 相信/v 中共/n 政体/n 无需/v 重大/a 改革/vn 便/d 足以/d 长治久安/nl 的/ude1 地步/n 。/wj 

玩弄/v 词藻/n ，/wd 空谈/v 民主/an 

九十/m 年代/n 后期/t 以来/f ，/wd 从/p 「/n 六四/n 风波/n 」/n 和/cc 「/n 苏/b 东/b 波/b 」/n 中/f 逐渐/d 缓/a 过/uguo 神/n 来/u 的/ude1 中共/n 高级/a 领导人/n ，/wd 不再/d 羞羞答答/z 、/wn 吞吞吐吐/vl 地/ude2 谈论/v 政/ng 改/v  了/y 。/wj 他们/rr 对/p 曾经/d 神经/n 过敏/vi 的/ude1 民主/an 、/wn 自由/a 、/wn 人权/n 等/udeng 议题/n 不再/d 讳莫如深/vl 比如/v ，/wd 不再/d 给/p 人权/n 贴/v 阶级/n 标签/n ，/wd 也/d 不/d 否认/v 「/n 民主/an 是/vshi 个/q 好/a 东西/n 」/n 。/wj 他们/rr 还/d 学会/v 了/ule 一本正经/al 、/wn 一/m 脸/q  无辜/n 地/ude2 谈论/v 普/ag 世/ng 价值/n ，/wd 轻松/a 熟练/a 地/ude2 玩弄/v 漂亮/a 词藻/n 尤其/d 是/vshi 在/p 面对/v 外国/n 政要/n 和/cc 公/b 眾/n 传媒/n 的/ude1 时候/n 。/wj 在/p 十七/m 大/a 的/ude1 报告/n 中/f ，/wd 胡锦涛/n 六十一/m 次/qv 提/v 到/v 了/ule 「/n 民主/an 」/n 。/wj 这/rzv 说明/v ，/wd 虽然/c  深/d 居/v 高/a 墻/n 大/a 内/f ，/wd 他们/rr 也/d 并/d 不/d 是/vshi 一/m 群/q 完全/ad 不/d 识/v 好歹/d 的/ude1 死硬/z 顽固/a 分子/n 。/wj 套用/v 汉娜/nrf ？/ww 阿伦特/nrf 评价/v 「/n 二十/m 世纪/n 初期/f 的/ude1 职业/n 革命家/n 」/n 的/ude1 一/m 句/q 话/n 来说/vi ：/wp 「/n 他们/rr 也许/d 是/vshi 歷/n 史/ng 的/ude1 傻瓜/n ，/wd  但/c 他们/rr 本/rz 人/n 肯定/d 不/d 是/vshi 傻瓜/n 。/wj 」/n 

然而/c 迄今/d 為/n 止/v ，/wd 我们/rr 仍然/d 看不到/v 中/f 共有/v 啟/n 动/v 实质性/n 政/ng 改/v 的/ude1 任何/rz 跡/n 象/ng 。/wj 不仅如此/bl ，/wd 中共/n 当局/n 对/p 政/ng 改/v 的/ude1 态度/n 反而/d 越来越/d 投机/v 取/v  巧/a 、/wn 虚应/v 其/rz 事/n ，/wd 其/rz 关/n 於/nr1 政/ng 改/v 的/ude1 一切/rz 理论/n 论述/vn 、/wn 政治/n 表态/vi ，/wd 要么/c 陈词滥调/nl 、/wn 强词夺理/vl ，/wd 要么/c 花/v 言/vg 巧/a 语/ng 、/wn 废话/n 连/ulian 篇/q 。/wj 如/v 什么/ry 「/n 党/n 的/ude1 领导/n 、/wn 人民/n 群/q 眾/n 当家作主/vl 和/cc 依法/d 治国/vi 的/ude1  有机/b 统一/vn 」/n ，/wd 什么/ry 「/n 扩大/v 民主/an 与/cc 党/n 管/v 干部/n 的/ude1 有机/b 统一/vn 」/n ，/wd 这/rzv 就/d 是/vshi 典型/a 的/ude1 政治/n 昏/tg 话/n ，/wd 不折不扣/vl 的/ude1 胡言乱语/vl ./wj 至/p 於/nr1 近些年/t 来/f 所谓/v 「/n 基层/n 民主/an 」/n 、/wn 「/n 党内/s 民主/a 」/n 的/ude1 改革/vn 试/v  点/qt ，/wd 也/d 通通/d 不成/v 体统/n ，/wd 令人/v 哭笑不得/al 。/wj 

中共/n 最/d 关心/v 的/ude1 是/vshi 怎样/ryv 不/d 改/v 

中共/n 的/ude1 政/ng 改/v 诚意/n 一直/d 令/v 人/n 生疑/vi 。/wj 我们/rr 发现/v 有/vyou 一个/mq 奇怪/a 的/ude1 现象/n ，/wd 从/p 邓小平/n 开始/v ，/wd 每当/p 中共/n 当局/n 刚刚/d 表白/v 其/rz 政/ng 改/v 决心/n ，/wd 他们/rr 接/v 下/vf  来/f 所/usuo 做/v 的/ude1 事情/n 却/d 并/d 不/d 是/vshi 制定/v 方案/n 、/wn 展开/v 行动/vn ，/wd 而是/c 急急忙忙/z 地/ude2 防/v 设卡/vi 、/wn 添/v 堵/v 立/v 禁/v 。/wj 政治/n 改革/vn 还/d 八字/n 没/d 一/m 撇/q ，/wd 邓小平/n 就/d 急不可待/vl 地/ude2 拋/n 出/vf 了/ule 「/n 四/m 项/q 基本/a 原则/n 」/n 和/cc 「/n 绝不/d  搞/v 三/m 权/n 分立/v 」/n 。/wj 很/d 明显/a ，/wd 他/rr 最/d 关心/v 的/ude1 事情/n 不/d 是/vshi 「/n 改/v 什么/ry 」/n 和/cc 「/n 怎么/ryv 改/v 」/n ，/wd 而是/c 「/n 不/d 改/v 什么/ry 」/n 和/cc 「/n 怎么/ryv 不/d 改/v 」/n 。/wj 尚未/d 铺路/vi 先/d 设卡/vi ，/wd 尚未/d 成行/vi 先/d 立/v 限/ng ，/wd 这/rzv 是/vshi 一个/mq 改革家/n 应/v  有/vyou 的/ude1 心态/n 吗/y ？/ww 这/rzv 就/d 是/vshi 中共/n 的/ude1 政/ng 改/v 诚意/n 吗/y ？/ww 当/p 「/n 六四/n 」/n 学潮/n 从/p 体制/n 外/f 给/p 中共/n 输送/v 去/vf 政治/n 改革/vn 的/ude1 巨大/a 推力/n ，/wd 邓/nr1 的/ude1 选择/vn 却/d 不/d 是/vshi 顺/v 天/qt 应/v 人/n 、/wn 借/v 风行/v 船/n ，/wd 而是/c 逆流/n 而/cc 动/v 、/wn 大/a 开/v 杀/v  戒/v ，/wd 既/c 犯/v 下/vf 了/ule 天/n 大/a 罪/n ，/wd 也/d 将/p 中国/ns 的/ude1 政/ng 改/v 事业/n 阻挡/v 了/ule 二十/m 年/qt 。/wj 邓/nr1 之后/f ，/wd 他/rr 的/ude1 两/m 位/q 继承人/n 在/p 政/ng 改/v 上/f 毫无/v 「/n 与/p 时/ng 俱/dg 进/vf 」/n 之/uzhi 处/n ，/wd 甚至/c 比/p 邓/nr1 更/d 少/v 了/ule 一些/mq 务实/vi 和/cc 坦白/a 。/wj 近/a 十/m 多/m 年/qt  来/vf ，/wd 他们/rr 越来越/d 敏/ag 於/nr1 言/ng 而/cc 訥/n 於/nr1 行/ng ，/wd 总/d 是/vshi 抽象/a 地/ude2 赞成/v 政/ng 改/v 而/cc 具体/a 地/ude2 反对/v 政/ng 改/v ，/wd 言词/n 上/f 声称/v 政/ng 改/v 而/cc 行动/vn 上/f 阻挠/v 政/ng 改/v ，/wd 其一/rz 切花/n 言/vg 巧/a 语/ng 和/cc 高谈阔论/vl ，/wd 无不/d 以/p 百般/d 刁难/v 、/wn 严防/v  死守/v 来/vf 跟/v 进/vf 、/wn 来/vf 落实/v 。/wj 

是/vshi 不/d 能/v 也/y ，/wd 亦/d 不/d 為/n 也/d 

对/p 於/nr1 中共/n 言行/n 乖张/z 的/ude1 政/ng 改/v 表现/v ，/wd 人们/n 有/vyou 很/d 多/m 种/q 解释/vn 。/wj 有人/r 说/v ，/wd 非/b 不能/v 也/y ，/wd 是/vshi 不/d 為/n 也/y 。/wj 这/rzv 话/n 颇/d 有/vyou 几/m 分/qt 道理/n 。/wj 至少/d ，/wd 在/p 邓小平生/nr  前/f ，/wd 如果/c 他/rr 执意/d 进行/vx 政治/n 改革/vn ，/wd 他/rr 是/vshi 有/vyou 能力/n 也/d 有/vyou 办法/n 做到/v 令/v 出/vf 必/d 行/vi ，/wd 而/cc 不必/d 太/d 担心/v 群僚/nr2 抵制/v 后院起火/vl 的/ude1 。/wj 但是/c ，/wd 邓小平/n 并非/v 真正/b 的/ude1 政/ng 改/v 派/v ，/wd 他/rr 只/d 知道/v 中共/n 政体/n 不/d 可/v 持/v  续/v ，/wd 却/d 不/d 知道/v 未来/t 的/ude1 政体/n 该/v 如何/ryv 抉择/v 、/wn 如何/ryv 构筑/v ./wj 简言之/vl ，/wd 他/rr 根本/d 就/d 不/d 具备/v 政体/n 创新/vn 所/usuo 必需/vi 的/ude1 远见卓识/nl 他/rr 比/p 先后/d 与/p 他/rr 分/v 道/n 扬/vg 鑣/n 的/ude1 胡耀邦/n 、/wn 赵紫阳/n 要/v 逊色/a 多/a 了/y 。/wj 邓/nr1  视/vg 多/m 元/q 民主/a 、/wn 三/m 权/n 分立/v 為/n 中共/n 的/ude1 大敌/n ，/wd 对/p 舆论/n 自由/an 、/wn 司法/n 独立/an 也/d 充满/v 了/ule 恶意/n ，/wd 所以/c ，/wd 尽管/c 他/rr 有/vyou 能力/n 、/wn 有/vyou 权威/n 发动/v 一/m 场/qv 大规模/b 的/ude1 政/ng 改/v ，/wd 但/c 他/rr 绝不/d 是/vshi 设计/v 和/cc 实施/v 政/ng 改/v 的/ude1 适/ag  当/p 人选/n ./wj 

至/p 於/nr1 邓/nr1 所/n 钦/ng 定/v 的/ude1 江泽民/n 、/wn 胡锦涛/n 及其/cc 高层/n 班子/n ，/wd 我们/rr 则/d 不/d 能/v 高估/v 他们/rr 的/ude1 个人/n 权威/n 和/cc 政治/n 能力/n 。/wj 他们/rr 摆/v 不/d 平/a 、/wn 搞/v 不/d 掂/v 的/ude1 事情/n 太/d  多/m ，/wd 非/b 止/v 政/ng 改/v 一/m 项/q 。/wj 对/p 他们/rr 而言/uls ，/wd 政/ng 改/v 是/vshi 不/d 能/v ，/wd 还是/c 不/d 為/n ？/ww 是/vshi 无/v 胆/n ，/wd 还/d 是/vshi 无/v 识/v ？/ww 恐怕/d 二者/rzv 兼而有之/vl 。/wj 得过且过/vl 、/wn 茍/n 且/c 偷安/v ，/wd 多一事不如少一事/vl ，/wd 与其/c 擅/vg 闯/v 高度/d 不/d 确定/v  的/ude1 领域/n ，/wd 不如/c 在/p 狭隘/a 的/ude1 既得利益/n 里/f 知足常乐/vl ，/wd 江/nr1 、/wn 胡/nr1 便/d 是/vshi 这样/rzv 的/ude1 人物/n 。/wj 世人/n 既/c 看/v 不/d 到/v 他们/rr 有/vyou 什么/ry 值得/v 称道/v 的/ude1 政治/n 远见/n ，/wd 即便/c 以/p 实力/n 、/wn 谋略/n 、/wn 雄心/n 、/wn 胆气/n 与/cc 魄力/n 而/cc 论/v ，/wd  他们/rr 也/d 只能/v 徒/ng 毛/n 邓/nr1 、/wn 辱没/v 胡/nr1 （/wkz 耀邦/nr2 ）/wky 赵/nr1 （/wkz 紫阳/ns ）/wky ，/wd 实在/d 不/d 堪/vg 担当/v 中共/n 政/ng 改/v 的/ude1 天/qt 降/v 大任/n 。/wj 

政治/n 改革/vn 不/d 可能/v 是/vshi 一/m 场/qv 皆大欢喜/vl 的/ude1 嘉年华/n 、/wn 一/m 幕/q 大团圆/vi 的/ude1 轻喜剧/n ，/wd 它/rr 必然/d 要/v 触及/v 权贵/n 与/cc 官僚/n 集团/n 的/ude1 既得利益/n 和/cc 未来/t 收益/n ，/wd 必/d  将/d 造成/v 权力/n 与/cc 利益/n 分配/vn 格局/n 的/ude1 巨大/a 翻转/vn ./wj 那些/rz 当/v 惯/v 了/ule 体制/n 寄生虫/n ，/wd 在/p 现行/b 政体/n 下/f 享/vg 足/a 了/ule 特权/n 、/wn 够/v 了/ule 便宜/a 还/d 希望/v 封/q 妻/ng 荫子/nr2 、/wn 世代相传/vl 的/ude1 中共/n 权贵/n ，/wd 他们/rr 内/f 心里/s 并/cc 不/d 乐/a  意/b 政治/n 改革/vn 。/wj 他们/rr 人数/n 虽/c 少/a ，/wd 却/d 身居/v 权力/n 要津/n 、/wn 领/v 体制/n 重地/n ，/wd 拥有/v 阻止/v 政/ng 改/v 的/ude1 条件/n 和/cc 能力/n 。/wj 这/rzv 大概/d 就/d 是/vshi 江/n 胡/Rg 们/k 的/ude1 政/ng 改/v 困/vi 局/n ：/wp 对/p 他们/rr 来说/uls ，/wd 做/v 特权/n 利益/n 的/ude1 守护/vn 者/k 比/p 做/v  政治/n 改革/vn 家/n 要/v 轻松/a 得/ude3 多/a 、/wn 容易/a 得/ude3 多/a 、/wn 顺当/a 得/ude3 多/a 。/wj 他们/rr 的/ude1 执政/vn 能力/n 与/cc 政治/n 权威/n 可/v 大/a 可/v 小/a ，/wd 因/p 為/n 共/vg 產/n 党/n 的/ude1 权力/n 本来/d 就是/v 这样/rzv 一个/mq 怪物/n ，/wd 拿/v 去/vf 谋私/vi 作恶/vi ，/wd 其/rz 权/n 无边/z ，/wd 用/v 来/vf 立/v  功/n 行善/vi ，/wd 其/rz 权/n 难/ad 用/v 。/wj 既/c 要/v 守护/v 特权/n 又/d 要/v 敷衍/v 民意/n ，/wd 他们/rr 也/d 就/d 只好/d 说/v 一/m 套/q 做/v 一/m 套/q ，/wd 见/v 人/n 说/v 人/n 话/n 、/wn 见鬼/v 说/v 鬼话/n 了/y 。/wj 政/ng 改/v 之/uzhi 於/nr1 此/rzs 辈/n ，/wd 是/vshi 不/d 能/v 也/y ，/wd 亦/d 不/d 為/n 也/d ；/wf 因/p 不/d 為/n 而/cc 不/d 能/v  也/d ，/wd 因/c 不/d 能/v 更/d 不/d 為/n 也/y 。/wj 一旦/c 他们/rr 认/v 準/n 了/ule 拖延/v 政/ng 改/v 的/ude1 「/n 维持/v 主义/n 」/n 之/uzhi 道/n ，/wd 那么/c ，/wd 政治/n 改革/vn 的/ude1 条件/n 永远/d 不/d 会/v 成熟/a ，/wd 时机/n 永远/d 不/d 会/v 到来/vi ，/wd 风险/n 永远/d 不/d 敢/v 承担/v ，/wd 代价/n 永远/d 不/d 可/v  支付/v 。/wj 

越/d 腐败/an 越/d 害怕/v 政/ng 改/v 

李慎之/nr 先生/n 八/m 年/qt 前/f 曾/d 说/v ，/wd 「/n 政治/n 改革/vn 的/ude1 条件/n 已经/d 烂熟/z 」/n 。/wj 若/c 以/p 苏/b 东/f 巨变/vi 、/wn 冷战/n 结束/v 后/f 的/ude1 全球/n 大/a 气候/n 和/cc 中国/ns 十三亿/m 人口/n 的/ude1 小气/a  候/v 来看/u ，/wd 此/rzs 论/v 绝对/d 正确/a ./wj 但/c 若/c 仅/d 以/p 中共/n 特权/n 利益/n 阶层/n 的/ude1 「/n 小/a 小气候/n 」/n 来看/u ，/wd 政/ng 改/v 的/ude1 条件/n 反而/d 越来越/d 夹/v 生/v 半/m 熟/a 了/y 。/wj 这/rzv 不/d 是/vshi 因/p 為/n 这个/rz 阶层/n 的/ude1 社会主义/n 信念/n 越来越/d 坚定/a 、/wn 共/d  產/n 主义/n 理想/n 越来越/d 纯洁/a ，/wd 而是/c 因/p 為/n 他们/rr 践踏/v 了/ule 越来越/d 多/a 的/ude1 良知/n 和/cc 正义/n ，/wd 贪/v 了/ule 越来越/d 多/a 的/ude1 不义之财/nl ，/wd 欠/v 下/vf 了/ule 越来越/d 多/a 的/ude1 无/v 头/q 烂/a 帐/ng 。/wj 腐败/an 已经/d 成/v 為/n 特权/n 利益/n 阶层/n 固定/a 的/ude1  联系/v 结构/n 和/cc 唯一/b 的/ude1 生存/vn 方式/n ，/wd 而/cc 越/d 腐败/an ，/wd 便/d 越/d 不/d 情愿/v 政/ng 改/v ，/wd 腐败/a 得/ude3 越/d 厉害/a ，/wd 便/d 越/d 害怕/v 政/ng 改/v 。/wj 

中共/n 还/d 有/vyou 政治/n 改革/vn 的/ude1 可能性/n 吗/y ？/ww 目前/t 还/d 看/v 不/d 到/v 。/wj 中共/n 权贵/n 一日/t 放/v 不/d 下/vf 特权/n 利益/n ，/wd 也/d 就/p 一日/t 不/d 可能/v 开/v 啟/n 实质性/n 政/ng 改/v 之/uzhi 门/n ./wj 发动/v  政/ng 改/v 的/ude1 领袖/n 迄今/d 尚未/d 產/n 生/v ，/wd 而/cc 期待/v 政/ng 改/v 的/ude1 民意/n 正在/d 加速/vd 流失/v 。/wj 当然/d ，/wd 总/d 会/v 有/vyou 那么/rz 一/m 天/qt ，/wd 到/v 了/ule 权贵/n 阶层/n 生死存亡/bl 之际/f ，/wd 中共/n 当局/n 终将/d 痛改前非/vl 、/wn 立即/d 政/ng 改/v ，/wd 就/d 如/v 武昌/ns 起/vf  义/ng 后/f 的/ude1 满清/t 政府/n 一样/uyy 。/wj 不过/c ，/wd 真/d 要/v 到/v 了/ule 那/rzv 一/m 天/qt ，/wd 曾经/d 奇/ag 货/n 可/v 居/v 的/ude1 政治/n 改革/vn ，/wd 也/d 就/d 多此一举/vl 、/wn 一钱不值/vl 了/y 。/wj 

