银行业/n 黄金/n 期/qv 已/d 终结/vi 
银行/n 股/q 半/m 年/qt 报/n 数据/n 显示/v ，/wd 今年/t 上半年/t 16/m 家/q 上市/vn 银行/n 实现/v 净利/n 5452.3亿/m 元/q ，/wd 同比/n 增长/v 18.25%/m 。/wj 但/c 利润/n 增速/n 明显/ad 回落/vi ，/wd 中间/f 业务/n 收入/n 增速/n 锐减/vi ，/wd 不良/a 贷款额/n 上升/vi ，/wd 同样/d 引发/v 外界/n 广泛/ad 关注/v 。/wj 
　　在/p 经历/n 连续/ad 下跌/vi 后/f ，/wd 9月/t 5日/t 16/m 只/q 银行/n A/x 股/n 就/d 有/vyou 8/m 只/q 跌破/v 净值/n ，/wd 占/v 比/p 刚好/d 一半/m 。/wj 而/cc 银行/n H/x 股/n 比/p A/x 股/n 更/d 早/ad 遭遇/v 市场/n 抛售/v 。/wj 
　　在/p 经济/n 持续/vd 下行/vi 背景/n 下/f ，/wd 尤其/d 随着/p 利率/n 市场化/vn 的/ude1 推进/vi ，/wd 原有/v 利率/n 管制/vn 形成/v 的/ude1 稳定/a 利差/n 模式/n 是否/v 行/ng 将/d 不复存在/vl ，/wd 中国/ns 银行业/n 的/ude1 黄金/n 期/qv 是否/v 已经/d 终结/vi ，/wd 银行业/n 转型/vn 之/uzhi 路/n 应该/v 怎么/ryv 走/v ？/ww 就/p 此/rzs ，/wd 《/wkz 中国/ns 经贸/b 聚焦/vn 》/wky (/wkz 下/f 称/v CBF/x )/wky 记者/n 日前/t 专访/v 了/ule 知名/a 金融/n 学者/n 、/wn 上海/ns 财经/n 大学/n 现代/t 金融/n 研究/vn 中心/n 副/b 主任/n 奚君羊/nr 教授/n 。/wj 
　　三座大山/nl 重压/n 之下/f 
　　CBF：/x 上半年/t 上市/vn 银行/n 净利/n 同比/n 增长/v 超过/v 18%/m ，/wd 但/c 利润/n 增速/n 回落/vi ，/wd 不良/a 贷款/n 上升/vi ，/wd 银行/n 股/n 也/d 被/pbei 看/v 空/ng ，/wd 股价/n 持续/vd 下跌/vi ，/wd 甚至/d 跌破/v 净值/n 。/wj 您/rr 认为/v 出现/v 这种/r 状况/n 的/ude1 主要/b 原因/n 是/vshi 什么/ry ？/ww 
　　奚君羊/nr ：/wp 原因/n 主要/d 是/vshi ，/wd 其一/rz ，/wd 中国/ns 经济/n 目前/t 正/d 处于/v 周期性/n 的/ude1 回落/vn 阶段/n ，/wd 而/cc 银行业/n 一般/uyy 被/pbei 认为/v 是/vshi 周期性/n 特征/n 很/d 明显/a 的/ude1 行业/n ——/wp 在/p 经济/n 上行/vi 的/ude1 时候/n ，/wd 银行/n 业绩/n 比较/d 好/a ，/wd 因为/c 企业/n 贷款/vn 需求/n 比较/d 旺盛/a ，/wd 利率/n 也/d 比较/d 高/a ，/wd 利差/n 较/d 大/a ；/wf 在/p 经济/n 回落/vn 阶段/n ，/wd 则/c 恰好/d 相反/vi 。/wj 同时/c ，/wd 中国/ns 经济/n 尽管/c 回落/vi 但/c 还/d 处于/v 相对/d 强劲/a 的/ude1 增长/vn 周期/n ，/wd 只是/c 从/p 高速/b 增长/vn 回落/vi 到/v 了/ule 中/f 速/ag 增长/v 。/wj 与/p 此/rzs 相/d 一致/a ，/wd 银行业/n 与其/c 周期性/n 同步/vi 的/ude1 特征/n 表现/v 就/d 是/vshi ：/wp 利润/n 仍/d 在/p 增长/vn ，/wd 但/c 增速/n 在/p 减缓/v 。/wj 
　　其二/rz ，/wd 中国/ns 正/d 在/p 推进/vi 利率/n 市场化/vn 进程/n 。/wj 此前/t ，/wd 央行/n 已经/d 两/m 次/qv 调/v 低/a 存贷款/n 基准/n 利率/n ，/wd 其中/rz ，/wd 7月/t 6日/t 的/ude1 第二/m 次/qv 降息/v 采取/v 了/ule 非/b 对称/ad 降息/v 的/ude1 做法/n ，/wd 即/d 下调/v 贷款/n 利率/n 而/cc 存款/n 利率/n 维持/v 不/d 变/v ；/wf 6月/t 8日/t 的/ude1 第一/m 次/qv 降息/v 还/d 将/p 金融/n 机构/n 存款/n 利率/n 浮动/vn 空间/n 的/ude1 上限/n 调整/v 为/p 基准/n 利率/n 的/ude1 1.1/m 倍/q ，/wd 将/p 贷款/n 利率/n 浮动/vn 空间/n 的/ude1 下限/n 调整/v 为/p 基准/n 利率/n 的/ude1 0.8/m 倍/q 。/wj 由于/p 各家/rz 银行/n 都/d 对/p 存款/n 利率/n 采取/v 了/ule 上浮/vn 的/ude1 做法/n ，/wd 这/rzv 使得/vi 银行/n 利差/n 缩小/v 。/wj 随着/p 未来/t 利率/n 市场化/vn 的/ude1 推进/vi ，/wd 银行/n 之间/f 的/ude1 竞争/vn 将/d 会/v 加剧/v ，/wd 利差/n 将/d 进一步/d 缩小/v ，/wd 银行/n 原本/d 主要/d 依赖/v 于/p 利差/n 收入/n 形成/v 的/ude1 利润/n 来源/n 又/d 将/d 受到/v 更/d 大/a 程度/n 的/ude1 挤压/vn 。/wj 
　　第三/m 方面/n ，/wd 在/p 2008年/t 出台/vi “/wyz 4万亿/m ”/wyy 经济/n 刺激/v 计划/n 后/f ，/wd 大量/m 银行/n 贷款/n 投向/v 了/ule 基础/n 设施/n 建设/vn 和/cc 地方/n 政府/n 融资/vn 平台/n 。/wj 现在/t 看来/v ，/wd 当初/t 的/ude1 这种/r 刺激/v 力度/n 过/uguo 猛/a ，/wd 造成/v 目前/t 的/ude1 产能/vn 过剩/vi ，/wd 物价/n 也/d 一度/d 飙/n 涨/vi ，/wd 中央/n 不得不/d 采取/v 适度/a 的/ude1 收缩/vn 政策/n ，/wd 存款/n 准备金/n 率/v 、/wn 利率/n 都/d 作出/v 了/ule 一定/b 的/ude1 调整/vn 。/wj 在/p 经济/n 持续/vd 下行/vi 时/ng ，/wd 地方/n 政府/n 融资/vn 平台/n 银行/n 过度/vd 涉足/v 的/ude1 一些/mq 项目/n 到期/vi 还款/v 可能/v 会/v 出现/v 一些/mq 困难/an ，/wd 包括/v 债务/n 拖欠/v 甚至/d 形成/v 坏/a 账/n 。/wj 银行/n 不良/a 贷款/n 已经/d 明显/ad 上升/vi ，/wd 而/cc 不/d 是/vshi 那/rzv 种/q 可以/v 忽略/v 不/d 计/vi 或是/c 幅度/n 很/d 小/a 的/ude1 上升/vn ，/wd 这/rzv 势必/d 侵蚀/v 一部分/m 利润/n 。/wj 当然/d ，/wd 目前/t 不良/a 贷款/n 的/ude1 上升/vn 还/d 未/d 对/p 银行/n 利润/n 或者/c 经营/v 带来/v 严重/a 的/ude1 不利/a 影响/vn ，/wd 银行/n 还/d 是/vshi 有/vyou 利润/n 的/ude1 ，/wd 利润/n 还/d 很/d 高/a 。/wj 
　　总体/n 而言/uls ，/wd 外界/n 对于/p 银行/n 的/ude1 利润/n 、/wn 坏/a 账/n 两/m 方面/n 都/d 有/vyou 一定/d 担忧/v ，/wd 所以/c 银行/n 业绩/n 被/pbei 看/v 空/ng 。/wj 此外/c ，/wd 结合/v 股市/n 来说/uls ，/wd 银行/n 股/n 持续/vd 下跌/vi 还/d 不/d 单单/d 是/vshi 银行/n 本身/rz 的/ude1 问题/n ，/wd 也/d 存在/v 着/uzhe 市场/n 投机性/n 选择/v 的/ude1 因素/n 。/wj 因为/p 银行/n 股/q 盘子/n 都/d 很/d 大/a ，/wd 要/v 拉/v 抬/v 其/rz 股价/n 很/d 困难/an ，/wd 加上/v 现在/t 股市/n 不景气/a ，/wd 有限/a 的/ude1 资金/n 投入/v 到/v 银行/n 股/n 上/f 几乎/d 只/d 是/vshi 打/v 水漂/n 。/wj 而/cc 中国/ns 股市/n 投资者/n 具有/v 一定/b 的/ude1 投机性/n ，/wd 主要/d 考虑/v 短期/b 内/f 的/ude1 差价/n 变化/vn ，/wd 对/p 有/vyou 一定/b 投资/vn 价值/n 但/c 不/d 温/nr1 不/d 火/a 、/wn 不/d 死/v 不/d 活/a 的/ude1 银行/n 股/n 就/d 失去/v 兴趣/n 。/wj 
　　利率/n 市场化/vn 前景/n 
　　CBF：/x 对于/p 未来/t 利率/n 市场化/vn 的/ude1 推进/vn 步骤/n 您/rr 怎么/ryv 理解/v ？/ww 
　　奚君羊/nr ：/wp 目前/t 利差/n 带来/v 的/ude1 利润/n 大概/d 占据/v 银行/n 净利/n 的/ude1 六/m 成/q 以上/f ，/wd 如果/c 再/d 加上/v 银行/n 通过/p 事实上/bl 的/ude1 变相/vn 的/ude1 存贷款/n 如/v 一些/mq 理财/vn 产品/n 和/cc 咨询/vn 费/n 、/wn 管理费/n 等/udeng 所/usuo 获得/v 的/ude1 利润/n ，/wd 总体/n 上/f 这/rzv 块/q 可能/n 要/v 占/v 银行/n 净利/n 的/ude1 七/m 成/q 甚至/d 更/d 高/a 。/wj 
　　从/p 近期/t 来看/v ，/wd 利率/n 市场化/v 应该/v 不/d 会/v 有/vyou 重大/a 的/ude1 推进/vn 步骤/n ，/wd 因为/c 还要/d 让/v 银行/n 有/vyou 一个/mq 逐步/d 适应/v 和/cc 消化/v 的/ude1 过程/n ，/wd 管理层/n 也/d 要/v 看/v 整个/b 宏观/n 经济/n 的/ude1 反应/vn 和/cc 效果/n 到底/d 如何/ryv 。/wj 
　　目前/t 对/p 存贷款/n 利率/n 的/ude1 上下/n 限/v 已经/d 有/vyou 一些/mq 放宽/v ，/wd 再/d 作/v 进一步/b 的/ude1 放宽/v 可能/v 对/p 银行/n 有/vyou 较/d 大/a 的/ude1 不利/a 影响/vn 。/wj 中国/ns 对/p 银行业/n 一直/d 是/vshi 严加/vd 保护/v 的/ude1 ，/wd 因为/c 作为/p 国民经济/n 的/ude1 血液/n 循环系统/nl ，/wd 银行业/n 一旦/d 出/vf 问题/n ，/wd 对/p 整个/b 经济/n 将/d 造成/v 毁灭性/n 的/ude1 打击/vn 。/wj 因此/c 利率/n 市场化/v 到/p 目前/t 这个/rz 阶段/n ，/wd 政府/n 不/d 会/v 有/vyou 贸然/d 的/ude1 推进/vn 措施/n 。/wj 但/c 从/p 长远/a 来/vf 看/v ，/wd 肯定/d 会/v 逐步/d 取消/v 对/p 存贷款/n 利率/n 浮动/vn 幅度/n 的/ude1 限制/vn ，/wd 未来/t 的/ude1 目标/n 将/d 是/vshi 银行/n 对/p 利率/n 实现/v 完全/ad 自主/vd 定价/vi 。/wj 
　　而/cc 要/v 实现/v 这/rzv 一/m 目标/n ，/wd 关键/n 是/vshi 监管/v 层/qv 要/v 找到/v 一个/mq 能够/v 替代/v 存贷款/n 基准/n 利率/n 的/ude1 宏观/n 经济/n 管理/vn 的/ude1 资金/n 价格/n 指标/n 。/wj 业/ng 内/f 目前/t 的/ude1 一般/ad 判断/v 是/vshi ，/wd 未来/t 这个/rz 指标/n 可能/v 就/d 是/vshi 上海/ns 银行/n 间/f 同业/n 拆借/vn 利率/n (/wkz Shibor/x )/wky 。/wj 在/p 过渡/vn 时期/n ，/wd 央行/n 会/v 考虑/v 两/m 方面/n 的/ude1 权衡/vn ，/wd 一/m 是/vshi 继续/v 使用/v 存贷款/n 基准/n 利率/n ，/wd 并/cc 逐步/d 放开/v 幅度/n 限制/vn ，/wd 二/m 是/vshi 加大/v Shibor/x 对/p 整个/b 银行业/n 资金/n 松紧/n 程度/n 的/ude1 影响/vn 力度/n 。/wj 最近/t 我们/rr 也/d 可以/v 发现/v ，/wd 央行/n 连续/ad 推出/v 天/qt 量/n 的/ude1 逆/vg 回/v 购/vg ，/wd 可能/v 就/d 是/vshi 试图/v 通过/p 加大/v 对/p 银行/n 间/f 拆借/vn 利率/n 的/ude1 影响/vn ，/wd 将/d Shibor/x 作为/v 一个/mq 资金/n 价格/n 的/ude1 工具/n ，/wd 进而/c 影响/v 整个/b 社会/n 的/ude1 资金/n 供求/n 状况/n 。/wj 
　　CBF：/x 随着/p 经济/n 持续/vd 下行/vi ，/wd 银行/n 的/ude1 不良/a 贷款/n 问题/n 是否/v 还/d 可能/v 持续/vd 恶化/vi ？/ww 
　　奚君羊/nr ：/wp 银行/n 不良/a 贷款/n 正/d 处于/v 上升/vi 时期/n ，/wd 还/d 未/d 见/v 顶/ng ，/wd 还/d 需要/v 一/m 年/qt 甚至/d 更/d 长/a 的/ude1 时间/n 才/d 有望/v 不再/d 继续/v 恶化/vi 或/c 回落/vi 。/wj 应该/v 说/v ，/wd 目前/t 银行/n 的/ude1 不良/a 贷款/n 问题/n 有/vyou 一定/b 的/ude1 严重性/n ，/wd 从/p 中国/ns 银行业/n 股份制/n 改革/v 近/a 10/m 年/qt 来/f 的/ude1 历史/n 比较/d 可以/v 发现/v ，/wd 不良/a 资产/n 上升/vi 速度/n 是/vshi 比较/d 快/a 的/ude1 ，/wd 其/rz 比率/n 也/d 已经/d 达到/v 一个/mq 较/d 高/a 的/ude1 水平/n ，/wd 但/c 还/d 远远/d 没有/d 到/v 会/v 让/v 银行/n 亏损/vn 甚至/d 倒闭/v 的/ude1 地步/n ，/wd 因为/c 银行/n 在/p 前/f 几/m 年/qt 利润/n 高速/b 增长/vn 时期/n 已经/d 提取/v 了/ule 大量/m 的/ude1 坏账/n 拨/v 备/v ，/wd 而且/c ，/wd 目前/t 银行/n 至少/d 还/d 能/v 保证/v 3/m 个/q 百分点/n 的/ude1 利差/n ，/wd 足以/d 弥补/v 坏账/n 损失/n 。/wj 
　　当然/d ，/wd 如果/c 地方/n 债务/n 包括/v 房地产/n 贷款/n 都/d 出现/v 严重/a 问题/n ，/wd 银行/n 将/d 遭遇/v 严重/a 困难/an 。/wj 不过/c ，/wd 这种/r 最/d 坏/a 的/ude1 情形/n 出现/v 的/ude1 概率/n 不/d 大/a 。/wj 而且/c 需要/v 指出/v 的/ude1 是/vshi ，/wd 地方/n 融资/vn 平台/n 贷款/n 毕竟/d 是/vshi 有/vyou 政府/n 信用/n 作/v 背景/n 的/ude1 ，/wd 如果/c 地方/n 出现/v 严重/a 债务/n 问题/n ，/wd 中央政府/n 不/d 会/v 袖手旁观/vl 。/wj 也/d 有/vyou 大量/m 可/v 操作/v 的/ude1 技术/n 手段/n ，/wd 在/p 很/d 大/a 程度/n 上/f 减缓/v 甚至/c 在/p 某种/rz 程度/n 上/f 化解/v 给/p 银行/n 带来/v 的/ude1 冲击/vn ，/wd 比如/v 账/n 期/qv 上/f 借/v 新/a 还/d 旧/a ，/wd 剥离/vi 部分/m 不良/a 资产/n 等/udeng 。/wj 地方/n 政府/n 最后/f 的/ude1 手段/n 还/d 包括/v 拍卖/v 部分/m 地方/n 国企/n 的/ude1 股权/n 。/wj 考虑/v 到/v 政府/n 实际/ad 拥有/v 的/ude1 这些/rz 巨/ag 量/n 资产/n ，/wd 其/rz 资产/n 负债/vn 是/vshi 不/d 会/v 出现/v 严重/a 问题/n 的/ude1 ，/wd 至少/d 在/p 资产/n 负债表/n 上/f 是/vshi 有/vyou 足够/vn 资产/n 可以/v 支撑/v 的/ude1 。/wj 
　　银行/n 如何/ryv 转型/v 
　　CBF：/x 半/m 年/qt 报/n 数据/n 还/d 显示/v ，/wd 银行/n 中间/f 业务/n 增速/n 急剧/d 下降/vi ，/wd 且/c 低于/v 整体/n 业绩/n 增速/n 。/wj 未来/t 随着/p 利率/n 市场化/vn 的/ude1 逐步/d 推进/vi ，/wd 银行/n 应当/v 怎么/ryv 避免/v 对于/p 利差/n 的/ude1 过度/vd 依赖/v ，/wd 如何/ryv 进行/vx 转型/vn ？/ww 
　　奚君羊/nr ：/wp 中间/f 业务/n 目前/t 只/d 是/vshi 银行/n 存贷款/n 传统/n 业务/n 的/ude1 一/m 种/q 补充/vn ，/wd 和/cc 传统/n 业务/n 一样/uyy ，/wd 中间/f 业务/n 也/d 面临/v 着/uzhe 类似/a 的/ude1 市场/n 资金/n 供求/n 关系/n ，/wd 增速/n 下滑/vi 自然/d 难免/v 。/wj 这/rzv 只不过/d 是/vshi 银行/n 本身/rz 的/ude1 一/m 种/q 结构性/n 的/ude1 分配/vn ，/wd 整个/b 市场/n 有/vyou 资金/n 供应/vn 需求/n ，/wd 汇总/v 到/v 银行/n 来/f ，/wd 银行/n 或者/c 以/p 中间/f 业务/n 或者/c 以/p 传统/n 业务/n 进行/vx 处理/vn 。/wj 事实上/bl ，/wd 中国/ns 银行业/n 所谓/v 的/ude1 中间/f 业务/n 更/d 多/a 是/vshi 其/rz 传统/n 业务/n 的/ude1 附庸/n ，/wd 并非/v 真正/b 意义/n 上/f 的/ude1 中间/f 业务/n ，/wd 比如/v 管理费/n 、/wn 咨询/vn 费/n ，/wd 这些/rz 都/d 是/vshi 在/p 银行/n 办理/v 贷款/n 业务/n 时/ng 派生/v 的/ude1 。/wj 
　　银行/n 要/v 进行/vx 转型/vn ，/wd 避免/v 过度/vd 依赖/v 存贷/n 差/a ，/wd 一方面/c ，/wd 从/p 银行/n 自身/rr 来说/uls ，/wd 应/v 加强/v 创新/vn 和/cc 产品/n 的/ude1 研发/v 能力/n ，/wd 通过/p 一些/mq 新/a 的/ude1 业务/n 品种/n 去/vf 满足/v 市场/n 多种/m 金融/n 需求/n ，/wd 摆脱/v 对于/p 传统/n 业务/n 的/ude1 过/vf 多/a 依赖/vn 。/wj 目前/t 银行/n 在/p 这/rzv 方面/n 的/ude1 能力/n 是/vshi 偏/d 弱/a 的/ude1 ，/wd 对于/p 中间/f 业务/n 创新/vi 的/ude1 投入/vn 远远/d 不/d 足/a ，/wd 其/rz 非传统/b 业务/n 部门/n 比如/v 理财/vn 部门/n 等/udeng 的/ude1 人员/n ，/wd 对于/p 金融/n 工具/n 、/wn 金融/n 市场/n 、/wn 金融/n 交易/vn 的/ude1 认识/n 和/cc 理解/vn 程度/n 也/d 远远/d 不够/a 。/wj 另一方面/c ，/wd 从/p 外部/f 而言/uls ，/wd 要/v 从/p 政策/n 层面/n 逐步/d 减少/v 对于/p 银行/n 的/ude1 过度/vd 保护/v 。/wj 利差/n 很/d 大/a 很/d 好/a 赚/v 钱/n ，/wd 银行/n 当然/d 就/d 会/v 一味/d 地/ude2 去/vf 拉/v 存款/n ，/wd 对/p 银行/n 的/ude1 充分/ad 保护/v 只/d 会/v 使/v 之/uzhi 缺乏/v 动力/n 也/d 没有/d 必要/a 去/vf 创新/vi 。/wj 应当/v 逐步/d 放松/v 保护/vn ，/wd 让/v 银行/n 进行/vx 充分/a 竞争/vn ，/wd 让/v 它/rr 感到/v 已经/d 很/d 难/ad 躺/v 在/p 过去/t 那种/r 靠/v 稳定/an 利差/n 赚钱/v 的/ude1 模式/n 上/vf 过/uguo 舒适/a 的/ude1 日子/n ，/wd 迫使/vi 它/rr 不/d 得/ude3 不/d 去/vf 闯/v 出/vf 一/m 条/q 新/a 路/n 。/wj 最后/f ，/wd 还/d 要/v 逐步/d 形成/v 综合/vd 经营/v 的/ude1 金融/n 体系/n 格局/n 。/wj 目前/t 中国/ns 金融业/n 还是/c 以/p 分业/v 经营/v 为主/vi ，/wd 银行/n 、/wn 保险/n 、/wn 证券/n 、/wn 信托/b ，/wd 到处/d 都/d 是/vshi 边界/n ，/wd 创新/vi 的/ude1 余地/n 就/d 很/d 少/a 。/wj 而/cc 所谓/v 创新/vi ，/wd 实际上/d 就是/v 在/p 各种/rz 金融/n 需求/n 与/cc 银行/n 能够/v 提供/v 的/ude1 服务/vn 之间/f 找到/v 一个/mq 切入点/n ，/wd 以/p 一/m 种/q 新/a 的/ude1 业务/n 品种/n 来/vf 满足/v 这种/r 需求/n 。/wj 
　　CBF：/x 上半年/t 16/m 家/q A/x 股/n 上市/vn 银行/n 净利/n 占/v 到/v 了/ule 所有/b 上市/vn 公司/n 净利润/n 的/ude1 54%/m 。/wj 您/rr 怎么/ryv 理解/v 银行/n 和/cc 实体/n 经济/n 之间/f 的/ude1 关系/n ，/wd 应当/v 如何/ryv 促进/v 银行/n 对于/p 实体/n 经济/n 的/ude1 支持/vn ？/ww 
　　奚君羊/nr ：/wp 对/p 促进/v 银行/n 之/uzhi 于/p 实体/n 经济/n 的/ude1 支持/vn ，/wd 外界/n 所/usuo 能/v 做/v 的/ude1 余地/n 其实/d 很/d 小/a 。/wj 因为/p 银行/n 毕竟/d 是/vshi 企业化/vi 的/ude1 经济/n 组织/n ，/wd 不/d 能/v 施加/v 强制性/b 的/ude1 行政/n 命令/n ，/wd 只/d 能/v 对/p 银行/n 资金/n 向/p 非/b 实体/n 性/ng 、/wn 虚拟/vn 性/ng 的/ude1 经济/n 领域/n 转移/v 设立/v 一定/b 的/ude1 界限/n ，/wd 比如/v 贷款/n 不/d 能/v 用于/v 炒股/vi 、/wn 炒作/v 房地产/n 等/udeng ，/wd 不/d 能/v 用/v 在/p 明显/ad 偏离/v 实体/n 经济/n 的/ude1 其他/rzv 地方/n 。/wj 从/p 政府/n 、/wn 从/p 外部/f 来说/uls ，/wd 对/p 银行/n 的/ude1 影响力/n 不/d 是/vshi 很/d 大/a 。/wj 实际上/d ，/wd 目前/t 银行/n 资金/n 流向/v 主要/d 也/d 还是/v 实体/n 经济/n ，/wd 流向/v 虚拟/vn 经济/n 的/ude1 并/cc 不/d 算/v 多/a 。/wj 
　　CBF：/x 您/rr 是否/v 认同/v 中国/ns 银行业/n 的/ude1 黄金/n 期/qv 已经/d 结束/v ？/ww 
　　奚君羊/nr ：/wp 中国/ns 银行业/n 过去/t 那种/r 高速/d 增长/v 的/ude1 周期/n 确实/ad 已经/d 一去不复返/vl 了/y ，/wd 就/d 好比/v 中国/ns 经济/n 再/d 想/v 达到/v 以前/f 那样/rzv 两/m 位/q 数/n 的/ude1 高速/b 增长/vn 已经/d 不/d 现实/a 。/wj 银行业/n 增速/n 会/v 放缓/v ，/wd 但/c 仍/d 会/v 有/vyou 比较/d 好/a 的/ude1 增长/vn ，/wd 因为/c 政府/n 对/p 银行/n 还/d 有/vyou 足够/v 的/ude1 保护/vn ，/wd 这种/r 保护/vn 将/d 逐步/d 消除/v ，/wd 但/c 不/d 会/v 一下子/mq 取消/v 。/wj 在/p 未来/t 一/m 段/q 时间/n 内/f ，/wd 银行/n 的/ude1 平均利润/nl 水平/n 还/d 会/v 比/p 其他/rzv 一般/a 的/ude1 工商/n 企业/n 要/v 高/a 。/wj 换言之/cc ，/wd 银行/n 股/n 还/d 是/vshi 具有/v 一定/b 的/ude1 投资/vn 价值/n 。/wj 