食/v 话/n 实/ad 说/v 第41/m 期/qv ：/wp 速溶/b 咖啡/n 提神/vi 还是/d 毁/v 健康/an ？/ww 
咖啡/n 提神/vi ≠/w 速溶/b 咖啡/n 也/d 提神/vi 在/p 咖啡/n 最/d 早/ad 为/v 非洲/nsf 土著/nz 发现/v 时/ng ，/wd 人们/n 发现/v 吃/v 了/ule 咖啡/n 很多/m 时候/n 会/v 莫名/a 地/ude2 亢奋/a 。/wj 经过/p 研究/vn 后/f ，/wd 人们/n 明白/v 之所以/c 饮用/v 咖啡/n 后/f 会/v 格外/d 亢奋/a 、/wn 达到/v 提神/vi 醒/v 脑/n 的/ude1 作用/n ，/wd 这/rzv 完全/ad 是/vshi 得益/vi 于/p 咖啡/n 中/f 所/usuo 含/v 有/vyou 的/ude1 大量/m 咖啡因/n 。/wj 咖啡因/n 具有/v 强烈/a 的/ude1 苦味/n ，/wd 能够/v 刺激/v 中枢神经/nl 系统/n 、/wn 心脏/n 和/cc 呼吸系统/nl ，/wd 使/v 人/n 忘却/v 疲劳/a 亢奋/a 起来/vf 。/wj 

但/c 据/p 日本/nsf 的/ude1 一/m 项/q 研究/vn 表明/v ，/wd 我们/rr 喝/vg 的/ude1 速溶/b 咖啡/n ，/wd 根据/p 人体/n 质/ng 的/ude1 不同/a ，/wd 也许/d 一/m 天/qt 喝/vg 五/m 杯/q 以上/f 也/d 不/d 能/v 达到/v 提神/vi 的/ude1 效果/n ，/wd 这/rzv 是/vshi 因为/p 速溶/b 咖啡/n 已经/d 脱离/v 了/ule 咖啡豆/n 中/f 原有/v 的/ude1 浓度/n ，/wd 额外/d 加入/v 其它/rz 增加/v 风味/n 的/ude1 奶油/n 、/wn 糖浆/n 、/wn 咖啡/n 伴侣/n 等/udeng ，/wd 一/m 份/q 速溶/b 咖啡/n 中/f ，/wd 真正/b 的/ude1 咖啡/n 成分/n 大约/d 只/d 有/vyou 原/d 磨/v 咖啡/n 的/ude1 四分之一/m 到/v 三分之一/m 。/wj 咖啡因/n 的/ude1 浓度/n 被/pbei 降低/v 之后/f ，/wd 速溶/b 咖啡/n 的/ude1 提神/vi 效果/n 也/d 就/d 大/a 打折扣/vi 了/y 。/wj 就/d 像/v 喝/vg 绿茶/n 能够/v 解乏/an ，/wd 但/c 市场/n 上/f 的/ude1 绿茶/n 饮料/n 却/d 没有/v 解乏/an 效果/n 一样/uyy 。/wj 当然/d 不/d 能/v 否认/v 一些/mq 神经/n 较为/d 敏感/a 的/ude1 人/n 即使/c 喝/vg 了/ule 速溶/b 咖啡/n 也/d 能/v 精神/n 振奋/v 。/wj 

咖啡/n 有/vyou 健康/a 效果/n ，/wd 不/d 代表/v 速溶/b 咖啡/n 也/d 对/p 健康/a 有/vyou 好处/n 根据/p 世界/n 各地/rzs 对/p 咖啡/n 与/cc 人体/n 之间/f 关联/vi 的/ude1 研究/vn 可知/v ，/wd 饮用/v 咖啡/n 的/ude1 数量/n 不/d 同/p 对于/p 不同/a 的/ude1 癌症/n 预防/v 都/d 是/vshi 有/vyou 效果/n 的/ude1 ，/wd 当然/d 相应/vi 也/d 会/v 产生/v 不同/a 的/ude1 副作用/n 。/wj 比如/v 咖啡/n 可以/v 降低/v 血压/n ，/wd 预防/v 卵巢/n 癌/n 、/wn 口腔/n 癌/n 等/udeng ，/wd 但/c 也/d 可能/v 导致/v 流产/vi 、/wn 引起/v 缺/v 钙/n 。/wj 虽然/c 咖啡/n 对/p 健康/a 的/ude1 有益/a 之/uzhi 处/n 无法/vd 忽视/v ，/wd 但/c 速溶/b 咖啡/n 中/b 真正/b 的/ude1 咖啡/n 成分/n 减少/v ，/wd 多/a 酚/n 类/q 物质/n 和/cc 咖啡/n 因/c 对/p 人体/n 的/ude1 作用/n 却/d 有待/v 商榷/vi 。/wj 更/d 让/v 人/n 感到/v 担心/v 的/ude1 是/vshi ，/wd 速溶/b 咖啡/n 在/p 生产/vn 过程/n 中/f ，/wd 为了/p 满足/v 人们/n 的/ude1 口感/n 需求/n ，/wd 往往/d 会/v 加入/v 大量/m 的/ude1 糖/n ，/wd 而/cc 糖/n 的/ude1 过/vf 多/m 摄入/v 不利于/v 人体/n 健康/an 。/wj 

在/p 某/rz 著名/a 速溶/b 咖啡/n 品牌/n 包装盒/n 上/f ，/wd 可以/v 看到/v 营养/n 成分/n 表/vg 显示/v 每份/r 速溶/b 咖啡/n 所/usuo 含/v 的/ude1 能量/n 为/v 260KJ/x ，/wd 蛋白质/n 0.3/m 克/q ，/wd 脂肪/n 2.4/m 克/q ，/wd 碳/n 水/n 化合物/n 9/m 克/q ，/wd 钠/n 40/m 毫克/q 。/wj 所谓/v 的/ude1 “/wyz 每份/r ”/wyy 速溶/b 咖啡/n 指/v 的/ude1 是/vshi 包装/n 好/a 的/ude1 一/m 小/a 条/q ，/wd 每/rz 条/q 的/ude1 量/n 为/p 13/m 克/q ，/wd 在/p 这/rzv 13/m 克/q 咖啡/n 中/f ，/wd 脂肪/n 和/cc 碳/n 水/n 化合物/n 这/rzv 两/m 个/q 产能/vn 大户/n 就/d 占/v 了/ule 11.4/m 克/q 。/wj 尽管/c 我们/rr 会/v 将/p 速溶/b 咖啡/n 冲/v 入/v 水/n 再/d 喝/vg 下去/vf ，/wd 但/c 其/rz 所/usuo 含/v 有的/rz 糖分/n 和/cc 能量/n 依旧/z 不容/v 我们/rr 忽视/v 。/wj 

想/v 要/v 提神/vi 茶/ng 比/p 咖啡/n 更/d 健康/a 中国/ns 人/n 从来/d 爱/v 喝茶/vi ，/wd 喝茶/vi 也/d 有/vyou 提神/vi 效果/n ，/wd 这/rzv 是/vshi 因为/p 茶叶/n 中/f 也/d 含有/v 和/cc 咖啡/n 相同/a 的/ude1 成分/n ——/wp 咖啡因/n 和/cc 多/a 酚/n 类/q 物质/n ，/wd 但/c 含量/n 浓度/n 上/f 和/cc 咖啡/n 有/vyou 一定/b 差异/n 。/wj 为什么/ryv 说/v 茶叶/n 比/p 咖啡/n 更/d 有利/a 健康/an ，/wd 这/rzv 是/vshi 因为/p 即使/c 不/d 经过/p 任何/rz 人工/n 加工/vn ，/wd 天然/b 咖啡/n 中/f 也/d 会/v 含有/v 糖分/n 和/cc 脂肪/n 。/wj 每/rz 100/m 克/q 咖啡豆/n 中/f 含有/v 16/m 克/q 脂肪/n 和/cc 46.7/m 克/q 糖类/n ，/wd 即使/c 你/rr 买/v 新鲜/a 的/ude1 咖啡豆/n 来/vf 自己/rr 磨/v 咖啡/n ，/wd 也/d 不可避免/vl 会/v 摄入/v 一/m 部分/n 的/ude1 糖分/n 和/cc 脂肪/n 。/wj 而/cc 茶叶/n 中/f 不/d 含/v 有/vyou 任何/rz 脂肪/n 和/cc 碳/n 水/n 化合物/n ，/wd 是/vshi 一/m 种/q 零/m 能量/n 的/ude1 饮品/n 。/wj 既然/c 提神/vi 效果/n 差不多/al ，/wd 自然/d 是/vshi 能量/n 更/d 低/a 的/ude1 茶叶/n 更加/d 健康/a ，/wd 当然/d ，/wd 对于/p 在/p 减肥/vi 的/ude1 人/n 来说/uls ，/wd 选择/v 茶叶/n 的/ude1 意义/n 也/d 会/v 更/d 明显/a 一些/mq 。/wj 

咖啡/n 饮品/n 该/v 怎么/ryv 选择/v ？/ww 国家标准/n 尚/d 缺/v 失/v 虽然/c 速溶/b 咖啡/n 对/p 健康/an 未必/d 有/vyou 好处/n ，/wd 但/c 喜欢/vi 速溶/b 咖啡/n 的/ude1 却/d 大有人在/vl ，/wd 如果/c 我们/rr 没/v 法/n 戒/v 掉/v 速溶/b 咖啡/n ，/wd 那么/c 可/v 不/d 可以/v 选择/v 更/d 健康/a 一些/mq 的/ude1 速溶/b 咖啡/n 呢/y ？/ww 我们/rr 可/v 不/d 可以/v 像/v 选择/v 牛奶/n 一样/uyy 将/p 某/rz 项/q 数据/n 作为/p 标准/n 的/ude1 切入点/n 进行/vx 选择/vn 呢/y ？/ww 遗憾/a 的/ude1 是/vshi ，/wd 国家/n 对于/p 咖啡/n 饮料/n 目前/t 尚未/d 有/vyou 明确/a 的/ude1 规范/n 和/cc 标准/n 。/wj 但/c 消费者/n 平时/t 在/p 购买/v 咖啡/n 及/cc 咖啡/n 饮料/n 产品/n 时/ng ，/wd 可以/v 注意/v 看/v 营养/n 成分/n 表/n ，/wd 碳/n 水/n 化合物/n 及/cc 能量/n 的/ude1 数值/n 相对/d 低/a 一些/mq 的/ude1 比较/d 好/a ，/wd 这/rzv 说明/v 外来/b 加入/v 的/ude1 糖分/n 相对/d 较/d 少/a ，/wd 也/d 相对/d 更/d 健康/a 一些/mq 。/wj 
