五/m ，/wd 中共/n 建/v 政/ng 第五/m 期/qv （/wkz 1989年/t 及/cc 之后/f ）/wky  

「/n 六四/n 」/n  屠杀/vn 中/f 到底/d 有/vyou 多少/ry 人/n 丧生/vi ，/wd 至今/d 中国政府/nt 没有/v 公/b 佈/n 。/wj 上述/b 纪思道/nr 和/cc 伍洁芳/nr 合著/v 的/ude1 《/wkz 中国/ns 觉/v 醒/v 了/ule 》/wky 谈到/v 「/n 六四/n 」/n 死亡/vi 人数/n 时/ng 说/v ，/wd 根据/p 北京/ns 一些/mq 医生/n 提供/v 的/ude1 信息/n ，/wd 估算/v 遇难/vi 者/k 在/p 400/m 到/v 800/m 之间/f ，/wd 几千/m 人/n 受伤/vi 。/wj 纪思道/nr 对/p 此/rzs 感/vg 嘆/n 说/v ，/wd 即使/c 按/p 保守/a 的/ude1 400/m 人/n 估算/vn ，/wd 也/d 超过/v 整个/b 19/m 世纪/n 中国/ns 政府/n 所/usuo 杀/v 的/ude1 抗议/vn 学生/n 总数/n 。/wj 纪思道/nr 书/n 中/f 引述/v 美国/nsf 国务院/n 的/ude1 数字/n 是/vshi ，/wd 约/d 3/m ,/wd 000/m 人/n 在/p 六四/n 事件/n 中/f 丧生/vi 。/wj 

1996年/t 出版/v 的/ude1 加拿大/nsf 《/wkz 环球/nz 邮报/n 》/wky 记者/n 黄明珍/nr （/wkz Jan/x  Wong/x ）/wky 的/ude1 回忆录/n 《/wkz 神州/n 怨/v 》/wky （/wkz Red/x  China/x  Blues/x ）/wky 中/f 的/ude1 数字/n ︰/n 「/n 在/p 六四/n 后/f 的/ude1 6月/t 8日/t ，/wd 我/rr 进入/v 北京/ns 工人/n 医院/n ，/wd 那/rzv 裡/n 的/ude1 医生/n 说/v ，/wd 太平间/n 裡/n 堆积/v 至少/d 100/m 具/q 尸体/n ，/wd 医院/n 又/d 增加/v 了/ule 一些/mq 冰柜/n ，/wd 每个/r 能/v 装/v 4/m 具/q 尸体/n ，/wd 也/d 都/d 塞/v 满/a 了/y ，/wd 但/c 仍/d 不/d 够/v 用/v 。/wj 」/n 

1996年/t 12月/t 18日/t ，/wd 美国/nsf 参议院/n 就/p 天安门/n 屠杀/v 举行/v 听证会/n ，/wd 在/p 会上/t 做/v 证/n 的/ude1 前/f 《/wkz 时代/n 》/wky 週/n 刊/vg 驻/v 北京/ns 採/n 访/v 主任/n 艾克曼/nrf （/wkz David/x  Aikman/x ）/wky 说/v ︰/n 一/m 位/q 合/v 眾/n 国际/n 社/n 记者/n 在/p 六四/n 之后/f 三/m 天/qt 内/f ，/wd 曾/d 打电话/vi 给/p 北京/ns 的/ude1 几/m 家/q 医院/n 询问/v 死亡/vi 人数/n ，/wd 最/d 多/a 一/m 家/q 医院/n 说/v 有/vyou 323/m 人/n 死亡/vi 。/wj 

2009年/t ，/wd 在/p 「/n 六四/n 」/n 20/m 週/n 年/qt 前夕/f ，/wd 前/f 中共/n 新华社/n 记者/n （/wkz 六四/n 期间/f 担任/v 该社/r 国内/s 新闻/n 部/q 主任/n ）/wky 张万舒/nr ，/wd 在/p 香港/ns 出版/v 了/ule 《/wkz 歷/n 史/ng 的/ude1 大/a 爆炸/vn ——/wp 六四/n 事件/n 全景/n 实录/n 》/wky 一/m 书/n 。/wj 该书/r 援引/v 当时/t 中国红十字会/nt 党组/n 书记/n 谭云鹤/nr 的/ude1 话/n 说/v ，/wd 「/n 六四/n 事件/n 死亡/vi 人数/n 有/vyou 727/m 人/n ，/wd 其中/rz 学生/n 和/cc 群/q 眾/n 死亡/vi 713/m 人/n ，/wd 军队/n 死亡/vi 14/m 人/n 。/wj 」/n 这个/rz 数字/n 显然/ad 比/p 当时/t 中国红十字会/nt 记录/v 的/ude1 2/m ,/wd 700/m 人/n 少/a 很多/m 。/wj 

从/p 1989年/t 天安门/n 屠杀/v 至/p 今/tg ，/wd 中国/ns 一直/d 是/vshi 全球/n 处决/v 死刑犯/n 最/d 多/a 的/ude1 国家/n 。/wj 由/p 中国/ns 留学生/n 主办/v 的/ude1 《/wkz 中国/ns 死刑/n 观察/v 》/wky 说/v ，/wd 「/n 中国/ns 每年/r 处决/v 的/ude1 犯人/n 人数/n ，/wd 超过/v 了/ule 世界/n 其他/rzv 国家/n 处决/v 犯人/n 的/ude1 总和/n 。/wj 」/n 有时/d 甚至/d 达到/v 全球/n 处决/v 人数/n 的/ude1 90%/m 。/wj 据/p 意大利/nsf 反对/v 死刑/n 的/ude1 民间/n 团体/n Hands/x  Off/x  Cain/x 的/ude1 报告/n ，/wd 2006年/t 全球/n 处决/v 5/m ,/wd 628/m 人/n ，/wd 其中/rz 约/d 5/m ,/wd 000/m 例/q 发生/v 在/p 中国/ns 。/wj 

这些/rz 被/pbei 处决/v 的/ude1 人/n ，/wd 包括/v 法轮功/n 学员/n 以及/cc 基督徒/n 等/udeng 。/wj 根据/p 海外/s 人权/n 团体/n 的/ude1 报告/n ，/wd 从/p 1999年/t 之后/f 十/m 年/qt ，/wd 超过/v 一千/m 名/q 法轮功/n 练习/v 者/k 被/pbei 强行/d 关/v 进/vf 精神病院/n ，/wd 两万/m 多/m 人/n 未/d 经/p 法律/n 程序/n 被/pbei 送/v 进/vf 劳改/vn 营/n ，/wd 一万/m 多/m 人/n 被/pbei 非法/d 逮捕/v 和/cc 监禁/v ；/wf 有/vyou 名/q 有/vyou 姓/n 的/ude1 法轮功/n 学员/n 达/v 3/m ,/wd 242/m 名/q 被/pbei 迫害/v 致死/vi 。/wj 

对/p 基督徒/n 的/ude1 镇压/vn 也/d 相当/d 严厉/a 。/wj 据/p 美国/nsf 德州/ns 「/n 对/p 华/b 援助/vn 协会/n 」/n 的/ude1 年度/n 报告/n ，/wd 仅/d 2007年/t ，/wd 家庭/n 教/v 会/v 遭/v 当局/n 迫害/vn 的/ude1 案例/n 就/d 波及/v 中国/ns 18/m 个/q 省/n ，/wd 有/vyou 788/m 人/n 受害/vi ，/wd 693/m 人/n 被捕/vi ；/wf 受到/v 拷打/v 、/wn 折磨/vn 的/ude1 基督徒/n 人数/n ，/wd 被/pbei 上年/t 增/v 多/m 325%/m ，/wd 被/pbei 虐待/v 人数/n 上升/vi 400%/m 。/wj 
