 日本/nsf 578/m 头/q 遭/v 核辐射/n 的/ude1 肉牛/n 入市/v  曝/vg 食品/n 安检/n 漏洞/n    
福/n 岛/n 县/n 和/cc 新/a 潟/n 县/n 当天/t 又/d 查出/v 有/vyou 435/m 头/q 被/pbei 放射性/n 铯/n 污染/vn 的/ude1 “/wyz 铯/n 牛/ag ”/wyy 进入/v 流通/vn 环节/n ，/wd 加上/v 此前/t 查明/v 的/ude1 143/m 头/q ，/wd 迄今/d 进入/v 日本/nsf 国内/s 近/v 40/m 个/q 都/d 道/v 府/ng 县/n 流通/vn 环节/n 的/ude1 “/wyz 铯/n 牛/ag ”/wyy 已经/d 增至/v 578/m 头/q 。/wj 由于/p 情况/n 升级/vi ，/wd 日本/nsf 可能/v 停止/v 流通/vn 所有/b 产/v 自/p 福/n 岛/n 县/n 的/ude1 牛肉/n 。/wj 福/n 岛/n 县/n 从/p 18日/t 开始/v 将/d 对/p 县/n 内/f 所有/b 4000/m 家/q 养牛/vn 农户/n 进行/vx 入/v 户/q 调查/vn ，/wd 宫/nr1 城/n 县/n 也/d 开始/v 对/p 县/n 内/f 900/m 多/m 家/q 专业/n 养牛/vn 农户/n 进行/vx 问询/v 调查/vn 。/wj  

　　福/n 岛/n 县政府/n 18日/t 发布/v 消息/n 称/v ，/wd 新/d 查明/v 县/n 内/f 有/vyou 7/m 家/q 肉牛/n 养殖户/n 给/p 牛/n 喂/v 食/v 了/ule 被/pbei 放射性/n 铯/n 污染/vn 的/ude1 稻草/n 。/wj 据悉/v ，/wd 这/rzv 7/m 家/q 养殖户/n 的/ude1 共/d 411/m 头/q 牛/n 已经/d 出栏/vi 。/wj 7/m 家/q 中/f 有/vyou 两/m 家/q 使用/v 的/ude1 稻草/n 来自/v 宫/nr1 城/n 县/n 、/wn 福/n 岛/n 县/n 内/f 被/pbei 测出/v 铯/n 的/ude1 稻草/n 农家/n 。/wj 从/p 本/rz 宫/ng 市/n 养殖户/n 使用/v 的/ude1 稻草/n 中/f 检测/v 出/vf 的/ude1 铯/n 强度/n 为/p 每/rz 千克/q 69万/m 贝克勒尔/nrf ，/wd 刷新/v 了/ule 实时/n 检测/vn 以来/f 的/ude1 最高/a 值/n 。/wj 福/n 岛/n 县政府/n 要求/v 这/rzv 7/m 家/q 养殖户/n 尽量/d 不/d 要/v 销售/v 或/c 移动/vn 肉牛/n ，/wd 并/cc 禁止/v 继续/v 给/p 肉牛/n 喂/v 食/v 稻草/n 。/wj  

　　含/v 铯/n 稻草/n 是/vshi 源头/n  

　　8日/t ，/wd 日本/nsf 在/p 东京/nsf 芝浦/nr2 屠宰场/n 最初/d 发现/v “/wyz 铯/n 牛/ag ”/wyy 问题/n 。/wj 福/n 岛/n 县/n 南/f 相/d 马/nr1 市/n 某/rz 养牛/vn 农户/n 出栏/vi 的/ude1 11/m 头/q 肉牛/n 中/f 有/vyou 1/m 头/q 牛/n 屠宰/v 后/f 在/p 肉/n 中/f 发现/v 放射性/n 铯/n 超标/vi 。/wj 第二/m 天/qt 在/p 其它/rz 10/m 头/q 肉牛/n 体内/s 也/d 检测/v 出/vf 放射性/n 铯/n 超标/vi 。/wj 这/rzv 11/m 头/q 肉牛/n 并未/d 进入/v 流通/vn 环节/n 。/wj 为/p 查明/v 牛肉/n 含/v 铯/n 的/ude1 原因/n ，/wd 福/n 岛/n 县政府/n 11日/t 对/p 南/f 相/d 马/nr1 市/n 某/rz 养牛/vn 农户/n 的/ude1 饲料/n 和/cc 水/n 进行/vx 了/ule 采样/vn 分析/vn ，/wd 结果/d 从/p 草料/n 中/f 检测/v 出/vf 了/ule 辐射/vn 强度/n 为/p 每/rz 千克/q 数万/m 贝克勒尔/nrf 的/ude1 铯/n 。/wj 这些/rz 稻草/n 在/p 福/n 岛/n 第一/m 核电站/n 事故/n 发生/v 时/ng 堆放/v 在/p 室外/s 。/wj 检测/vn 人员/n 得出/v 的/ude1 结论/n 是/vshi ：/wp “/wyz 铯/n 牛/ag ”/wyy 的/ude1 成因/n 在于/v 含/v 铯/n 稻草/n 。/wj 后/f 经/p 调查/v 发现/v ，/wd 南/f 相/d 马/nr1 市/n 这家/r 养牛/vn 农户/n 分别/d 于/p 5月/t 和/cc 6月/t 出栏/vi 6/m 头/q 肉牛/n ，/wd 并/cc 已/d 销售/v 到/v 12/m 个/q 都/d 道/v 府/ng 县/n 。/wj  

　　14日/t ，/wd 有关/vn 人员/n 发现/v 福/n 岛/n 县/n 浅/a 川/b 町/n 一家/n 养牛/vn 农户/n 稻草/n 放射性/n 铯/n 超标/vi ，/wd 同时/c 得知/v 这/rzv 家/q 农户/n 此前/t 出栏/vi 的/ude1 42/m 头/q 肉牛/n 已经/d 进入/v 流通/vn 环节/n 。/wj 宫/nr1 城/n 县/n 15日/t 在/p 登/v 米市/n 、/wn 栗/ng 原/b 市/n 3/m 家/q 养牛/vn 农户/n 的/ude1 稻草/n 中/f 也/d 检测/v 出/vf 放射性/n 铯/n 。/wj 福/n 岛/n 县政府/n 16日/t 查明/v ，/wd 郡/n 山/n 市/n 、/wn 喜/v 多方/r 市/n 和/cc 相/d 马/nr1 市/n 5/m 家/q 肉牛/n 养殖户/n 出栏/vi 的/ude1 84/m 头/q 肉牛/n 是/vshi 用/p 含/v 放射性/n 铯/n 的/ude1 稻草/n 喂养/v 的/ude1 。/wj 日本/nsf 政府/n 称/v ，/wd 曾/d 于/p 3月/t 19日/t 下发/v 通知/n ，/wd 要求/v 畜产/n 农户/n 不/d 要/v 使用/v 暴露/v 在/p 室外/s 的/ude1 饲料/n ，/wd 但/c 多数/m 农户/n 表示/v 没有/d 接到/v 过/uguo 类似/a 通知/n 。/wj 此外/c ，/wd 日本/nsf 的/ude1 防范/vn 措施/n 过于/d 依赖/v 农户/n 的/ude1 自行/d 申报/v ，/wd 但/c 在/p 最先/d 曝/vg 出/vf “/wyz 铯/n 牛/ag ”/wyy 问题/n 的/ude1 南/f 相/d 马/nr1 市/n ，/wd 有的/rz 农户/n 没有/d 在/p 牛/n 出栏/vi 前/f 如实/d 填写/v 喂/v 食/v 水稻/n 秸秆/n 和/cc 水/n 的/ude1 情况/n 。/wj  

　　牛肉/n 消费/vn 遭/v 重创/v  

　　为什么/ryv 这么/rz 多/ad 吃/v 了/ule 含/v 铯/n 稻草/n 的/ude1 “/wyz 铯/n 牛/ag ”/wyy 能够/v 通过/p 检验/v 进入/v 流通/vn 环节/n ？/ww 福/n 岛/n 第一/m 核电站/n 周边/n 地区/n 的/ude1 肉牛/n 在/p 出栏/vi 前/f 都/d 要/v 进行/vx 放射性/n 物质/n 体表/n 检查/vn ，/wd 但/c 此次/rz “/wyz 铯/n 牛/ag ”/wyy 是/vshi 食用/v 了/ule 遭/v 核/n 污染/vn 的/ude1 稻草/n 而/cc 受到/v 了/ule 内/f 照射/v ，/wd 并非/v 体表/n 检查/vn 就/d 可以/v 查出/v 。/wj 肉牛/n 在/p 屠宰/v 之后/f 还要/d 经过/p 检测/vn ，/wd 但/c 只是/d 抽样/vd 检测/v ，/wd 抽样/vn 比例/n 不/d 超过/v 10%/m ，/wd 因此/c 含/v 铯/n 牛肉/n 很/d 可能/v 躲/v 过/vf 了/ule 抽样/vn 检测/vn 。/wj 日本/nsf 农林/n 水产/n 省/n 和/cc 福/n 岛/n 县政府/n 已经/d 表示/v ，/wd 中央政府/n 计划/n 与/cc 县政府/n 合作/vn ，/wd 对/p 相关/vn 区域/n 的/ude1 所有/b 养牛/vn 农户/n 出栏/vi 的/ude1 牛肉/n 实施/v 放射性/n 物质/n 全面/ad 检测/v ，/wd 除了/p 和/cc 以前/f 一样/uyy 实施/v 体表/n 检测/vn 外/f ，/wd 还/d 将/d 对/p 宰杀/v 后/f 的/ude1 牛肉/n 进行/vx 全面/a 而/cc 不/d 是/vshi 抽样/vn 检测/vn 。/wj  

　　“/wyz 铯/n 牛/ag ”/wyy 进入/v 流通领域/nl 重创/v 了/ule 日本/nsf 牛肉/n 消费/vn 市场/n 。/wj 在/p 东京/nsf ，/wd 一些/mq 店铺/n 和/cc 超市/n 开始/v 停/vi 售/v 日本/nsf 国产/b 牛肉/n ，/wd 转而/c 销售/v 澳大利亚/nsf 等/udeng 国/n 的/ude1 进口/vn 牛肉/n 。/wj 不少/m 以/p 经营/vn 牛肉/n 食品/n 为主/vi 的/ude1 饭店/n 的/ude1 生意/n 也/d 大/a 受/v 影响/vn ，/wd 顾客/n 明显/ad 减少/v 。/wj 在/p 横滨/ns 市/n ，/wd 一些/mq 中小学校/n 和/cc 幼儿园/n 应/v 家长/n 要求/n ，/wd 在/p 伙食/n 中/f 不再/d 提供/v 牛肉/n 。/wj  

　　日本/nsf 《/wkz 朝日/nz 新闻/n 》/wky 16日/t 发表/v 社论/n 称/v ，/wd 超过/v 预想/v 的/ude1 放射/vn 物/ng 污染/v 扩大/v ，/wd 说明/v 日本/nsf 食品/n 安全/an 检查/vn 体制/n 还/d 不/d 健全/v 。/wj 核/n 污染/v 今后/t 还/d 将/d 扩散/v 到/v 哪些/ry 食品/n ，/wd 无法/v 预见/v 。/wj 只有/c 构筑/v 安全/an 安心/a 的/ude1 流通/vn 环境/n ，/wd 才/d 能/v 消除/v 民众/n 的/ude1 不安/an 。/wj 有/vyou 专家/n 指出/v ，/wd 随着/p 时间/n 推移/vn ，/wd 福/n 岛/n 核/n 事故/n 造成/v 的/ude1 污染/vn 主要/d 以/p 半衰期/n 长/a 的/ude1 放射性/n 铯/n 为主/vi ，/wd 其中/rz 铯/n 137/m 的/ude1 半衰期/n 为/p 30/m 年/qt ，/wd 一些/mq 数量/n 相对/d 较/d 少/a 的/ude1 铯/n 同位素/n 的/ude1 半衰期/n 则/c 更/d 长/a 。/wj 这/rzv 很/d 可能/v 意味/n 着/uzhe 日本/nsf 的/ude1 食品/n 安全/an 问题/n 将/d 对/p 居民/n 健康/ad 构成/v 长期/b 威胁/vn 。/wj  
