日本/nsf “/wyz 辐射/vn 牛/n ”/wyy 风波/n 挑战/vn 食品/n 安全/an 控制/vn 体系/n   
 随着/p 福/n 岛/n 产/v “/wyz 辐射/vn 牛/n ”/wyy 经/p 流通领域/nl 扩散/v 至/p 日本/nsf 全国/n 各地/rzs 乃至/c 消费者/n 的/ude1 餐桌/n ，/wd 日本/nsf 国产/b 牛肉/n 消费/vn 市场/n 面临/v 自/p 疯牛病/n 风波/n 以来/f 的/ude1 最/d 大/a 危机/n 。/wj “/wyz 辐射/vn 牛/n ”/wyy 问题/n 显示/v ，/wd 核/n 泄漏/vn 的/ude1 广泛/a 程度/n 和/cc 潜在/b 危害/vn 可能/n 超出/v 此前/t 日本/nsf 政府/n 公开/ad 承认/v 的/ude1 范围/n ，/wd 也/d 给/p 日本/nsf 食品/n 安全/an 风险/n 控制/vn 体系/n 提出/v 新/a 挑战/vn 。/wj 

    日本/nsf 共同/b 社/n 的/ude1 消息/n 说/v ，/wd 截至/v 7月/t 17日/t ，/wd 已/d 有/vyou 143/m 头/q 涉嫌/v 放射性/n 铯/n 含量/n 超标/vi 的/ude1 福/n 岛/n 牛/n 进入/v 流通/vn 市场/n 。/wj 这些/rz 牛/n 的/ude1 肉/n 已/d 流散/v 至/p 包括/v 东京/nsf 在内/u 的/ude1 日本/nsf 37/m 个/q 都/d 道/v 府/ng 县/n ，/wd 其中/rz 大多数/m 牛肉/n 已/d 通过/p 超市/n 、/wn 餐饮店/n 等/udeng 渠道/n ，/wd 被/pbei 消费者/n 食用/vn 。/wj 

    据/p 日本/nsf 政府/n 相关/vn 部门/n 和/cc 福/n 岛/n 县/n 方面/n 的/ude1 调查/vn ，/wd “/wyz 辐射/vn 牛/n ”/wyy 的/ude1 主要/b 成因/n 是/vshi 福/n 岛/n 县/n 的/ude1 一些/mq 农户/n 用/p 田间/s 采集/v 的/ude1 水稻/n 秸秆/n 喂/v 牛/n 。/wj 水稻/n 秸秆/n 并非/v 牛/n 的/ude1 主食/n ，/wd 主要/d 用于/v 增加/v 肉质/n 的/ude1 肥美/a 程度/n 。/wj 但/c 检测/v 结果/n 显示/v ，/wd 这些/rz 秸秆/n 受到/v 严重/a 的/ude1 放射性/n 污染/vn ，/wd 郡/n 山/n 市/n 一/m 家/q 农场/n 的/ude1 水稻/n 秸秆/n 饲料/n 中/f 测出/v 的/ude1 铯/n 放射性/n 活/v 度/qv 高/a 达/v 每/rz 公斤/q 50万/m 贝克勒尔/nrf ，/wd 是/vshi 日本/nsf 政府/n 规定/n 的/ude1 暂定/v 安全/an 标准/n 上限/n 的/ude1 上千/m 倍/q 。/wj 

    尤其/d 引人瞩目/vl 的/ude1 是/vshi ，/wd 尽管/c 上述/b 地区/n 露天/n 堆放/v 的/ude1 水稻/n 秸秆/n 含/v 高/a 放射性/n 物质/n ，/wd 但/c 这些/rz 地区/n 均/d 不/d 在/p 日本/nsf 政府/n 划定/v 的/ude1 警戒/vn 区/n 或/c 计划/n 疏散/v 区/n 内/f ，/wd 而是/c 位于/v 距/p 福/n 岛/n 第一/m 核电站/n 60/m 公里/q 至/p 100/m 公里/q 以外/f 的/ude1 地方/n 。/wj 

    “/wyz 辐射/vn 牛/n ”/wyy 的/ude1 出现/v 使/v 福/n 岛/n 人/n 和/cc 许多/m 日本/nsf 人/n 自/p 核/n 事故/n 以来/f 怀有/v 的/ude1 隐忧/n ——/wp 核/n 污染/vn 的/ude1 扩散/vn 和/cc “/wyz 热点/n ”/wyy 问题/n 再次/d 浮现/vi 。/wj 所谓/v “/wyz 热点/n ”/wyy ，/wd 是/vshi 指/v 在/p 日本/nsf 政府/n 划定/v 的/ude1 核/n 污染区/n 外/f ，/wd 因/p 地形/n 、/wn 风向/n 、/wn 降雨/vn 等/udeng 形成/v 的/ude1 点/qt 状/ng 分布/vi 高/a 污染/vn 区/n ，/wd 尤/d 以/p 福/n 岛/n 县/n 内/f 最为/d 严重/a 。/wj 按照/p 一些/mq 核辐射/n 专家/n 的/ude1 看法/n ，/wd 在/p 距离/n 核/n 泄漏/vn 电站/n 80/m 公里/q 的/ude1 福/n 岛/n 市内/s ，/wd 一些/mq 区域/n 的/ude1 辐射/vn 量/n 甚至/d 超过/v 切尔诺贝利/nz 事件/n 中/f 的/ude1 强制/vd 疏散/v 标准/n 。/wj 以/p 东京/nsf 为/p 中心/n 的/ude1 首都/n 圈/qv 内/f ，/wd 也/d 不断/d 测出/v “/wyz 热点/n ”/wyy 。/wj 如/v 千/m 叶县/ns 柏/ng 市/n 、/wn 东京都/nsf 葛/nr1 饰/v 区/n 等/udeng 地/n ，/wd 其/rz 测出/v 的/ude1 累积/vn 辐射/vn 水平/n 超过/v 每年/r 1/m 毫/ng 希沃特/nrf 。/wj 而/cc 国际/n 辐射/vn 防护/vn 委员会/n 在/p 核/n 泄漏/vn 事故/n 应急/vn 处理/vn 指南/n 中/f 建议/v ，/wd 核/n 事故/n 平息/vi 后/f 可/v 接受/v 的/ude1 安全/an 辐射/vn 量/n 下限/n 是/vshi 每年/r 1/m 毫/ng 希沃特/nrf 。/wj 此前/t ，/wd 日本/nsf 静冈县/ns 的/ude1 部分/n 茶叶/n 产区/n 发现/v 放射性/n 铯/n 超标/vi 的/ude1 茶叶/n ，/wd 也/d 与/p “/wyz 热点/n ”/wyy 的/ude1 形成/vn 有关/vn 。/wj 

    专家/n 指出/v ，/wd 随着/p 时间/n 推移/vn ，/wd 福/n 岛/n 核/n 事故/n 造成/v 的/ude1 污染/vn 主要/d 以/p 半衰期/n 长/a 的/ude1 放射性/n 铯/n 为主/vi ，/wd 其中/rz 铯/n 137/m 的/ude1 半衰期/n 为/p 30/m 年/qt ，/wd 一些/mq 数量/n 相对/d 较/d 少/a 的/ude1 铯/n 同位素/n 的/ude1 半衰期/n 则/c 更/d 长/a 。/wj 这/rzv 意味着/v 日本/nsf 境内/s 的/ude1 “/wyz 热点/n ”/wyy 可能/v 长期/d 得/ude3 不/d 到/v “/wyz 冷却/v ”/wyy ，/wd 对/p 食品/n 安全/an 和/cc 居民/n 健康/ad 构成/v 长期/b 威胁/vn 。/wj 

    “/wyz 辐射/vn 牛/n ”/wyy 风波/n 还/d 暴露/v 出/vf 日本/nsf 食品/n 安全/an 风险/n 控制/vn 体系/n 的/ude1 漏洞/n 。/wj 一/m 是/vshi 牛肉/n 检测/vn 程序/n 问题/n ，/wd 日本/nsf 农林/n 水产/n 省/n 此前/t 只/d 要求/v 在/p 出栏/vi 前/f 对/p 福/n 岛/n 牛/n 的/ude1 体表/n 进行/vx 核辐射/n 检测/vn ，/wd 而/cc “/wyz 辐射/vn 牛/n ”/wyy 当时/t 全部/m 过关/vi ，/wd 直到/v 后来/t 抽查/v 牛肉/n 时/ng ，/wd 才/d 发现/v 严重/a 的/ude1 牛/n 体内/s 辐射/vn 问题/n 。/wj 二/m 是/vshi 在/p 牛/n 饲料/n 处理/vn 问题/n 上/f ，/wd 农林/n 水产/n 省/n 曾/d 于/p 3月/t 19日/t 向/p 各地/rzs 下发/v 通知/n ，/wd 要求/v 农户/n 只/d 能/v 使用/v 核/n 事故/n 前/f 收获/v 的/ude1 室内/s 储存/v 饲料/n 喂/v 牛/n ，/wd 但/c 这/rzv 一/m 通知/n 并/cc 未/d 把/pba 作为/v 辅料/n 的/ude1 水稻/n 秸秆/n 包括/v 在/p 内/f 。/wj 三/m 是/vshi 在/p 防范/v 措施/n 方面/n ，/wd 过于/d 依赖/v 农户/n 自行/d 申报/v ，/wd 比如/v 最先/d 曝/vg 出/vf “/wyz 辐射/vn 牛/n ”/wyy 问题/n 的/ude1 南/f 相/d 马/nr1 市/n 农户/n 后来/t 承认/v ，/wd 该/rz 农户/n 没有/d 在/p 牛/n 出栏/vi 前/f 如实/d 填写/v 喂/v 食/v 水稻/n 秸秆/n 和/cc 水/n 的/ude1 情况/n 。/wj 

    “/wyz 辐射/vn 牛/n ”/wyy 给/p 日本/nsf 牛肉/n 消费/vn 市场/n 带来/v 重创/vn 。/wj 东京/nsf 的/ude1 一些/mq 商场/n 和/cc 超市/n 开始/v 停/vi 售/v 日本/nsf 国产/b 牛肉/n ，/wd 许多/m 消费者/n 转而/c 购买/v 澳大利亚/nsf 等/udeng 国/n 的/ude1 进口/vn 牛肉/n 。/wj 各地/rzs 烤肉/n 店/n 、/wn 主营/vn 牛肉/n 饭/n 的/ude1 餐饮店/n 等/udeng 也/d 饱受/v 影响/vn ，/wd 食客/n 明显/ad 见/v 少/a 。/wj 在/p 横滨/ns ，/wd 一些/mq 中小学校/n 和/cc 幼儿园/n 应/v 家长/n 要求/n ，/wd 在/p 伙食/n 中/f 不再/d 提供/v 牛肉/n 。/wj 

    日本/nsf 相关/vn 监管部门/n 和/cc 福/n 岛/n 县/n 正/d 全力/d 追查/v “/wyz 辐射/vn 牛/n ”/wyy 的/ude1 流向/n 和/cc 消费/vn 情况/n 。/wj 根据/p 规定/n ，/wd 日本/nsf 每/rz 头/n 牛/n 都/d 有/vyou 一个/mq 特定/b 号码/n ，/wd 可/v 顺藤摸瓜/vl 掌握/v 每/rz 一个/mq 流通/vn 环节/n 。/wj 政府/n 原子能/n 灾害/n 对策/n 本部/n 也/d 有望/v 于/p 19日/t 下达/v 针对/p 福/n 岛/n 牛/n 的/ude1 出栏/vn 禁令/n 。/wj 不过/c ，/wd 由于/c 在/p 政府/n 下达/v 禁令/n 前/f ，/wd 已/d 有/vyou 上千/m 头/q 福/n 岛/n 牛/n 进入/v 市场/n ，/wd 其中/rz 很/d 多/a 牛/n 的/ude1 肉/n 已/d 被/pbei 食用/v ，/wd 逐一/d 排查/v 非常/d 困难/an 。/wj 此外/c ，/wd 检测/v 出栏/vi 肉牛/n 的/ude1 体内/s 核辐射/n 水平/n 费时/a 费力/a ，/wd 如果/c 发起/v 大规模/b 检测/vn ，/wd 相关/vn 仪器/n 和/cc 人/n 手/n 都/d 难免/v 捉襟见肘/vl 。/wj 

    日本/nsf 《/wkz 朝日/nz 新闻/n 》/wky 16日/t 在/p 一/m 篇/q 社论/n 中/f 指出/v ，/wd 今后/t 一/m 段/q 时期/n ，/wd 日本/nsf 可能/v 持续/vd 面对/v 食品/n 核辐射/n 污染/vn 问题/n ，/wd 谁/ry 也/d 不/d 知道/v 下/vf 一个/mq 可能/n 被/pbei 污染/v 的/ude1 是/vshi 什么/ry 产品/n 。/wj 如何/ryv 确保/v 受/v 放射性/n 污染/vn 的/ude1 其他/rzv 食品/n 不再/d 进入/v 流通/vn 环节/n ，/wd 将/d 是/vshi 日本/nsf 政府/n 需/v 长期/d 认真/ad 应/v 对/p 的/ude1 难题/n 。/wj  
 
 
