食/v 话/n 实/ad 说/v 第19/m 期/qv ：/wp 素食/n 真的/d 能/v 减肥/vi 吗/y ？/ww 
何谓/v 素食/n ？/ww 从/p 严格/a 意义/n 上/f 讲/v ，/wd 素/ag 食指/n 的/ude1 是/vshi 禁用/v 动/v 物性/n 原料/n 及/cc 禁用/v “/wyz 五/m 辛/nr1 ”/wyy 和/cc “/wyz 五荤/n ”/wyy 的/ude1 寺院/n 菜/n 、/wn 道观/n 菜/n 。/wj 但是/c 对于/p 现在/t 的/ude1 人们/n 来说/uls 凡是/d 从/p 土地/n 中/f 和/cc 水/n 中/f 生长/v 出来/vf 的/ude1 植物/n ，/wd 可/v 供/vi 人们/n 直接/ad 使用/v 或/c 加工/v 使用/v 的/ude1 食品/n ，/wd 我们/rr 都/d 可以/v 统称/v 为/p 素食/n 。/wj 比如说/vl 蔬菜/n ，/wd 果品/n ，/wd 豆制品/n 和/cc 面筋/n 等/udeng 材料/n 制作/v 的/ude1 素菜/n 等/udeng 食物/n 。/wj 从/p 素食/n 的/ude1 严格/a 程度/n 上/f 来说/uls ，/wd 素食/n 还/d 可/v 分为/v 全/a 素/ag 素食/n 、/wn 蛋/n 奶/n 素食/n 、/wn 奶/n 素食/n 、/wn 果素/nr 等/udeng 。/wj 目前/t 为止/u 世界/n 上/f 有/vyou 不少/m 严格/a 的/ude1 素食/n 主义/n 者/k ，/wd 有的/rz 是/vshi 为了/p 宗教/n 信仰/vn ，/wd 有的/rz 是/vshi 为了/p 环境/n ，/wd 有的/rz 是/vshi 为了/p 维护/v 健康/an ，/wd 但/c 更/d 多/a 的/ude1 都/d 是/vshi 出于/v 一个/mq 理由/n ——/wp 减肥/vi 。/wj 

素食/n 真的/d 能/v 减肥/vi 吗/y ？/ww 从/p 严格/a 意义/n 上/f 来说/uls ，/wd 如果/c 素食/n 只/d 吃/v 蔬菜/n 和/cc 水果/n ，/wd 不/d 摄入/v 肉/n 、/wn 禽/ng 、/wn 鱼/n 、/wn 蛋/n 和/cc 任何/rz 的/ude1 动物/n 性/ng 、/wn 植/v 物性/n 油脂/n ，/wd 由于/c 蔬菜/n 和/cc 水果/n 水分/n 多/a 、/wn 能量/n 低/a ，/wd 因此/c 摄入/v 的/ude1 热量/n 也/d 会/v 相当/d 少/a 。/wj 每/rz 100g/x 白菜/n 只/d 含有/v 52KJ/x 的/ude1 能量/n ，/wd 每/rz 100g/x 苹果/n 只/d 含有/v 218KJ/x 的/ude1 能量/n ，/wd 而/cc 根据/p 2002年/t 中国/ns 居民/n 营养/n 与/cc 健康/a 状况/n 调查/vn 的/ude1 结果/n ，/wd 我国/n 18/m ~/n 59/m 岁/qt 的/ude1 男性/n 每日/r 平均/ad 摄入/v 热量/n 为/v 9200KJ/x ，/wd 女性/n 摄入/v 热量/n 为/v 7550KJ/x ，/wd 因此/c 从/p 数量/n 上/f 的/ude1 巨大/a 差异/n 来看/u ，/wd 严格/a 素食/n 所/usuo 摄入/v 的/ude1 能量/n 远远/d 无法/v 达到/v 人/n 一/m 天/qt 的/ude1 生命/n 活动/vn 所/usuo 需要/v 的/ude1 能量/n ，/wd 因此/c 人体/n 内/f 储存/v 的/ude1 脂肪/n 必然/d 会/v 分解/v 转化/v 为/p 能量/n 供/vi 人体/n 的/ude1 正常/a 活动/vn ，/wd 因此/c 从/p 理论/n 上/f 来说/uls ，/wd 素食/n 是/vshi 可以/v 达到/v 减肥/vi 的/ude1 效果/n 的/ude1 。/wj 

但是/c 从/p 实际/n 意义/n 上/f 来/vf 看/v ，/wd 这种/r 严格/a 素食/n 的/ude1 做法/n 却/d 是/vshi 不/d 大/a 现实/n 的/ude1 。/wj 现在/t 有/vyou 一/m 种/q 理论/n 逐渐/d 为/v 大家/rr 所/usuo 承认/v ，/wd 那/rzv 就是/d 不/d 吃/v 早餐/n 更/d 容易/a 胖/a 。/wj 研究/v 认为/v 不/d 吃/v 早餐/n 会/v 造成/v 上午/t 饥饿/n ，/wd 而/cc 在/p 进食/vi 中餐/n 的/ude1 时候/n ，/wd 身体/n 反而/d 会/v 存储/vn 更/d 多/a 的/ude1 能量/n 以/p 弥补/v 没/d 吃/v 早餐/n 的/ude1 能量/n 不/d 足/a ，/wd 因此/c 不/d 吃/v 早餐/n 反而/d 更/d 容易/a 胖/a 。/wj 同/p 理/n 可以/v 推/v 导出/v 严格/a 素食/n 这样/rzv 的/ude1 做法/n 同样/d 是/vshi 不/d 可取/a 的/ude1 。/wj 由于/p 蔬菜/n 和/cc 水果/n 热量/n 低/a ，/wd 虽然/c 饱/a 腹/ng 感/vg 不/d 差/a 但/c 很快/d 就/d 会/v 感到/v 饿/v ，/wd 如果/c 进行/vx 严格/a 的/ude1 素食/n 减肥/vi ，/wd 在/p 现代/t 社会/n 高压/n 高/a 工作量/n 的/ude1 现状/n 下/f ，/wd 这些/rz 能量/n 远远/d 不能/v 满足/v 人体/n 正常/a 生活/vn 的/ude1 需求/n ，/wd 因此/c 坚持/v 不/d 了/ule 几/m 天/qt 素食/n 减肥/vn 计划/n 可能/v 就/d 宣布/v 泡汤/vi 。/wj 而/cc 这个/rz 时候/n ，/wd 一旦/d 开始/v 恢复/v 正常/a 饮食/n ，/wd 身体/n 会/v 摄入/v 更/d 多/a 的/ude1 能量/n 进行/vx 储存/vn ，/wd 体重/n 反弹/vi 会/v 变/v 得/ude3 很/d 严重/a ，/wd 自虐/vi 一般/ad 忍/v 饿/vd 吃素/v 也/d 变/v 得/ude3 没有/v 意义/n 了/y 。/wj 

另外/c ，/wd 如果/c 不/d 是/vshi 严格/a 的/ude1 素食/n 主义/n 者/k ，/wd 有/vyou 不少/m 人/n 在/p 进食/vi 蔬菜/n 水果/n 时/ng ，/wd 同时/c 也/d 喜欢/vi 吃/v 坚果/n 、/wn 豆类/n ，/wd 喜欢/vi 喝/vg 汽水/n ，/wd 这样/rzv 的/ude1 做法/n 不但/c 不/d 能/v 减肥/vi ，/wd 反而/d 有/vyou 增/v 肥/a 的/ude1 嫌疑/n 。/wj 因为/p 坚果/n 虽然/c 含有/v 大量/m 的/ude1 维生素/n E/x 、/wn 叶酸/n 、/wn 镁/n 钾/n 铜/n 等/udeng 矿物质/n 、/wn 不/d 饱和/vi 脂肪酸/n 以及/cc 较/d 多/a 的/ude1 膳食/n 纤维/n ，/wd 对/p 健康/a 有益/a ，/wd 但/c 其/rz 所/usuo 含/v 有/vyou 的/ude1 能量/n 也/d 非常/d 高/a ，/wd 如果/c 不/d 严格/ad 计算/v 坚果/n 的/ude1 摄入/v 量/n ，/wd 就/d 反而/d 会/v 吃/v 进/vf 更/d 多/a 的/ude1 热量/n 。/wj 而/cc 汽水/n 中/f 含有/v 大量/m 的/ude1 碳/n 水/n 化合物/n ，/wd 这/rzv 也/d 是/vshi 能量/n 的/ude1 主要/b 来源/n 。/wj 因此/c ，/wd 不/d 科学/a 的/ude1 素食/n 既/c 不/d 能/v 减肥/vi ，/wd 还/d 会/v 承担/v 营养/n 摄入/v 不/d 均衡/ad 造成/v 的/ude1 健康/a 恶果/n ，/wd 比/p 不/d 吃/v 素食/n 后果/n 更/d 严重/a 。/wj 

哪些/ry 人/n 适合/v 素食/n ？/ww 素食/n 作为/v 近/a 几/m 年/qt 来/f 不少/m 人/n 推崇/v 的/ude1 养生/vn 方法/n ，/wd 虽然/c 减肥/vn 效果/n 因人而异/vl ，/wd 但/c 有/vyou 一些/mq 人/n 执行/vn 素食/n 主义/n 却/d 是/vshi 十分/d 有/vyou 必要/a 的/ude1 ，/wd 这些/rz 人群/n 包括/v 了/ule 高血压/n 、/wn 高/a 血脂/n 、/wn 高/a 血糖/n 的/ude1 三/m 高/a 人群/n ，/wd 以及/cc 患有/v 心脏病/n 、/wn 心脑血管/n 疾病/n 的/ude1 人群/n 。/wj 这些/rz 人群/n 可以/v 通过/p 素食/n 的/ude1 方式/n ，/wd 减少/v 动/v 物性/n 脂肪/n 和/cc 胆固醇/n 的/ude1 摄入/v ，/wd 减少/v 油/n 、/wn 盐/n 和/cc 糖/n 的/ude1 摄入/v ，/wd 对/p 减轻/v 身体/n 负担/n 是/vshi 有/vyou 一定/b 好处/n 的/ude1 。/wj  

如何/ryv 才/d 能/v 科学/a 素食/n ？/ww 第一/m ，/wd 根据/p 体质/n 科学/a 素食/n 。/wj 在/p 决定/v 要/v 进行/vx 素食/n 的/ude1 时候/n ，/wd 一定/d 要/v 先/d 问/v 自己/rr ：/wp “/wyz 我/rr 的/ude1 体质/n 适合/v 素食/n 吗/y ？/ww ”/wyy 如果/c 自己/rr 经常/d 出现/v 营养/n 不良/a 、/wn 低/a 血糖/n 、/wn 贫血/vn 等/udeng 症状/n ，/wd 这样/rzv 的/ude1 人群/n 就/d 不/d 适宜/v 素食/n 了/y 。/wj 如果/c 是/vshi 三/m 高/a 人群/n ，/wd 可以/v 在/p 医生/n 的/ude1 建议/n 下/f 制定/v 素食/n 方案/n ，/wd 决定/v 好/a 素食/n 周期/n 和/cc 频率/n ，/wd 并/cc 随时/d 根据/p 自身/rr 体质/n 的/ude1 变化/vn 而/cc 不断/d 变化/v 素食/n 计划/n ，/wd 这样/rzv 才/d 能/v 更加/d 健康/a 有效/a 地/ude2 素食/n 。/wj 

第二/m ，/wd 素食/n 人群/n 要/v 注意/v 补充/v 其他/rzv 营养/n 。/wj 由于/p 蔬菜/n 水果/n 中/f 含有/v 大量/m 的/ude1 维生素/n 、/wn 膳食/n 纤维/n 和/cc 矿物质/n ，/wd 但/c 钙/n 、/wn 蛋白质/n 、/wn 脂肪酸/n 等/udeng 人体/n 必需/vi 的/ude1 营养素/n 却/d 无法/v 通过/p 蔬菜/n 水果/n 摄入/v ，/wd 因此/c 素食/n 人群/n 需要/v 注意/v 增加/v 豆类/n 、/wn 蛋/n 奶/n 、/wn 坚果/n 等/udeng 食物/n 的/ude1 摄入/v ，/wd 通过/p 这些/rz 食物/n 摄入/v 身体/n 所/usuo 需/v 的/ude1 钙/n 、/wn 蛋白质/n 和/cc 脂肪酸/n 。/wj 但/c 最/d 好/a 的/ude1 做法/n 就是/d 不/d 偏废/v 肉类/n 和/cc 鱼类/n ，/wd 但/c 减少/v 摄入/v 的/ude1 次数/n 和/cc 摄入/v 的/ude1 量/n ，/wd 以/p 蔬菜/n 水果/n 以及/cc 杂粮/n 为主/vi ，/wd 肉类/n 为辅/vi ，/wd 并/cc 注意/v 摄入/v 高蛋白/n 食物/n ，/wd 保证/v 营养/n 均衡/an 。/wj 

第三/m ，/wd 注意/v 素食/n 方式/n 。/wj 首先/c 在/p 素食/n 的/ude1 时候/n ，/wd 尽量/d 保证/v 口味/n 清淡/a ，/wd 以/p 清蒸/vn 和/cc 水/n 煮/v 为主/vi ，/wd 尽量/d 避免/v 油/n 炸/v 和/cc 红烧/b 。/wj 另外/c ，/wd 有/vyou 不少/m 人/n 认为/v “/wyz 素食/n =/m 生/v 食/ng ”/wyy ，/wd 凉/a 拌和/vn 沙拉/n 热量/n 更/d 少/a ，/wd 但/c 这/rzv 是/vshi 一/m 种/q 不/d 全面/a 的/ude1 看法/n 。/wj 一方面/c ，/wd 由于/c 食物/n 未经/d 加热/vi ，/wd 存在/v 细菌/n 杀灭/v 不/d 完全/a 的/ude1 隐患/n ，/wd 尤其/d 是/vshi 叶/nr1 菜/n ；/wf 另一方面/c ，/wd 长期/d 食用/v 生/v 食/ng ，/wd 容易/ad 对/p 脾胃/n 造成/v 不良/a 影响/vn 。/wj 因此/c ，/wd 如果/c 担心/v 炒菜/vi 会/v 因为/p 油/n 而/cc 带入/v 不必要/a 的/ude1 热量/n ，/wd 可以/v 用/p 热水/n 焯/v 一/m 焯/v 。/wj 

来自/v 39/m 小/a 编/v 的/ude1 健康/ad 提醒/v ：/wp 科学/n 素食/n 不但/c 能够/v 减少/v 热量/n 摄入/v ，/wd 达到/v 减肥/vn 效果/n ，/wd 还/d 可以/v 定期/d 给/p 身体/n 减/vd 负/v ，/wd 排/v 出/vf 体内/s 毒素/n ，/wd 不失为/v 一/m 种/q 健康/a 的/ude1 养生/vn 方式/n 。/wj 但/c 网友/n 需要/v 注意/v 几/m 点/qt ：/wp 一/m 是/vshi 根据/p 自身/rr 的/ude1 体质/n 选择/vn 素食/n 的/ude1 方式/n ；/wf 二/m 是/vshi 在/p 素食/n 的/ude1 过程/n 中/f 注意/v 摄入/v 其他/rzv 的/ude1 营养素/n ，/wd 保证/v 均衡/ad 全面/ad 摄入/v 营养/n ；/wf 三/m 是/vshi 在/p 素食/n 过程/n 中/f ，/wd 选择/v 更加/d 健康/a 的/ude1 烹饪/vn 方式/n ，/wd 以/p 清淡/a 为主/vi 。/wj 健康/a 素食/n ，/wd 加上/v 适量/a 运动/vn 才/d 能/v 真正/d 达到/v 减肥/vi 的/ude1 效果/n ，/wd 切/d 勿/d 一味/d 盲目/a 素食/n ，/wd 否则/c 既/c 损害/v 了/ule 身体/n 健康/an ，/wd 又/d 无法/v 达到/v 减肥/vi 的/ude1 效果/n 。/wj 


