食/v 话/n 实/ad 说/v 第25/m 期/qv ：/wp 食用/v 明胶/n 无毒/vi 害/v  添加/v 产品/n 非/b 素食/n 
明胶/n 到底/d 是/vshi 什么/ry ？/ww 从/p 概念/n 上/f 来说/uls ，/wd 明胶/n 是/vshi 一/m 种/q 用/v 由/p 煮/v 过/uguo 的/ude1 动物/n 骨头/n ，/wd 皮肤/n 和/cc 筋腱/n 制成/v 的/ude1 肽/ng 分子/n 聚合/vn 物质/n ，/wd 是/vshi 胶/n 原/b 蛋白质/n 的/ude1 水解/v 产物/n ，/wd 含有/v 大量/m 的/ude1 氨基酸/n ，/wd 有/vyou 较/d 高/a 的/ude1 营养/n 价值/n 。/wj 这个/rz 东西/n 其实/d 并非/v 远离/v 生活/vn 不/d 可/v 常见/a ，/wd 老百姓/n 在/p 家中/s 熬/v 大/a 骨/ng 汤/n 冷凝/vn 后/f ，/wd 汤/n 的/ude1 表面/n 会/v 出现/v 一/m 层/qv 清澈/a 透明/a 微微/d 有/vyou 琥珀/n 色/ng 的/ude1 冻/v 状/ng 物体/n ；/wf 还有/v 一些/mq 地区/n 会/v 食用/v 一/m 种/q “/wyz 冻/v ”/wyy ，/wd 做成/v 长条/n 状/ng ，/wd 口感/n 如果/c 冻/v ，/wd 但/c 含/v 在/p 口中/s 遇/v 热/k 会/v 化/v ，/wd 是/vshi 不少/m 老百姓/n 喜欢/vi 的/ude1 凉拌/vn 菜肴/n …/ws …/ws 这些/rz 东西/n 其实/d 都/d 是/vshi 明胶/n ，/wd 因此/c ，/wd 明胶/n 并非/v 远离/v 我们/rr 的/ude1 生活/vn ，/wd 也/d 并/d 不/d 是/vshi 什么/ry 可怕/a 的/ude1 东西/n ，/wd 大家/rr 无/v 需/v 对/p 明胶/n 二/m 字/n 过分/a 恐慌/an 。/wj 

食用/v 明胶/n 和/cc 工业/n 明胶/n 有/vyou 什么/ry 区别/n ？/ww 其实/d ，/wd 食用/v 明胶/n 和/cc 工业/n 明胶/n 都/d 是/vshi 明胶/n ，/wd 从/p 外表/n 来/vf 看/v 基本/ad 没有/v 差别/n ，/wd 一般/a 消费者/n 无法/vd 鉴别/v ，/wd 而/cc 其/rz 区别/n 在于/v 原料/n 和/cc 用途/n 的/ude1 不同/a 。/wj 之所以/c 酸奶/n 、/wn 果冻/n 等/udeng 食物/n 里/f 会/v 有/vyou 明胶/n ，/wd 是/vshi 因为/p 明胶/n 具有/v 吸水性/n 强/ng 、/wn 粘度/n 高/a 的/ude1 理化/n 特性/n ，/wd 再/d 加上/v 是/vshi 一/m 种/q 无/v 脂肪/n 的/ude1 高蛋白/n ，/wd 不/d 含/v 胆固醇/n ，/wd 因此/c 明胶/n 就/d 成为/v 了/ule 一/m 种/q 天然/b 营养/n 型/k 的/ude1 食品/n 增/v 稠/a 剂/q ，/wd 为/p 酸奶/n 、/wn 果冻/n 、/wn 小/a 笼/ng 包/v 等/udeng 食物/n 增加/v 一定/b 的/ude1 口感/n 而/cc 使用/v ，/wd 同时/c 还/d 具有/v 一定/b 的/ude1 保鲜/vn 作用/n 。/wj 往/p 食物/n 里/f 添加/v 的/ude1 明胶/n 被/pbei 称为/v 食用/vn 明胶/n ，/wd 食用/v 明胶/n 是/vshi 使用/v 新鲜/a 动物/n 皮/n 经/p 严格/a 的/ude1 安全/an 生产/vn 控制/vn 熬/v 煮/v 提取/v 的/ude1 胶/n 原/b 蛋白质/n ，/wd 无毒/vi 无害/vi ，/wd 只要/c 按照/p 国家/n 要求/v 在/p 外/f 包装/v 上/f 标明/v ，/wd 就/d 不/d 违法/vi ，/wd 民众/n 也/d 不/d 需要/v 担心/v 有/vyou 安全/an 问题/n ，/wd 从/p 营养/n 角度/n 来说/uls ，/wd 食用/v 明胶/n 的/ude1 添加/vn 并/cc 不/d 会/v 影响/vn 食物/n 原本/n 的/ude1 营养/n 价值/n 。/wj 

而/cc 近来/d 闹/v 得/ude3 民众/n 不/d 愉快/a 的/ude1 主人公/n 则/d 是/vshi 明胶/n 的/ude1 另/rz 一/m 重/q 用途/n ——/wp 工业/n 明胶/n 。/wj 工业/n 明胶/n 被/pbei 广泛/ad 应用/v 于/p 板材/n 、/wn 家具/n 、/wn 火柴/n 、/wn 包装/n 、/wn 造纸/vn 等/udeng 行业/n 的/ude1 各种/rz 产品/n 中/f ，/wd 并/cc 在/p 其中/rz 主要/d 起/vf 增/v 稠/a 、/wn 稳定/an 、/wn 凝聚/v 等/udeng 作用/n 。/wj 因为/p 非/b 用于/v 食用/vn ，/wd 因此/c 熬/v 制/v 过程/n 比较/d 简单/a ，/wd 其中/rz 还/d 添加/v 防腐剂/n ，/wd 严禁/v 用/v 于/p 食用/vn 。/wj 现在/t 的/ude1 普遍/a 的/ude1 做法/n 是/vshi 收集/v 皮革/n 边角料/n ，/wd 通过/p 一/m 系列/q 工序/n ，/wd 从/p 皮革/n 中将/n 水解蛋白/n 脱出/v ，/wd 制成/v 明胶/n ，/wd 这样/rzv 可以/v 有效/ad 利用/v 废弃/v 皮革/n ，/wd 降低/v 成本/n 。/wj 但/c 问题/n 在于/v 废弃/v 皮革/n 中/f 含有/v 不少/m 金属/n 铬/ng ，/wd 而/cc 在/p 脱/v 水解蛋白/n 的/ude1 过程/n 中/f 铬/ng 无法/v 脱/v 干净/a ，/wd 因此/c 工业/n 明胶/n 带有/v 毒性/n ，/wd 如果/c 只/d 用/v 于/p 工业/n 制作/vn ，/wd 不/d 会/v 对/p 人体/n 的/ude1 健康/ad 造成/v 损害/v 。/wj 

加入/v 明胶/n 的/ude1 食物/n 非/b 素食/n 明胶/n 作为/v 一/m 种/q 食品/n 增/v 稠/a 剂/q ，/wd 用于/v 肉冻/n 、/wn 罐头/n 、/wn 糖果/n 、/wn 香肠/n 、/wn 粉丝/n 、/wn 方便面/n 、/wn 雪糕/n 等/udeng 食品/n 行业/n ，/wd 而/cc 食物/n 中/f 加入/v 增/v 稠/a 剂/q 的/ude1 目的/n 之一/rz 是/vshi 为了/p 增加/v 劲/n 道/qv 的/ude1 口感/n ，/wd 如/v 粉条/n 、/wn 方便面/n 等/udeng ；/wf 二/m 是/vshi 为了/p 防止/v 在/p 运输/vn 过程/n 中/f 产生/v 撞击/v 导致/v 产品/n 外形/n 崩溃/vi ，/wd 如/v 酸奶/n 等/udeng 。/wj 有/vyou 不少/m 网友/n 误认为/v 粉丝/n 、/wn 粉条/n 、/wn 酸奶/n 等/udeng 属于/v 素食/n ，/wd 这/rzv 是/vshi 一/m 种/q 误/d 读/v 。/wj 因为/p 粉丝/n 等/udeng 在/p 生产/vn 的/ude1 过程/n 中/f 加入/v 了/ule 明胶/n ，/wd 而/cc 明胶/n 是/vshi 从/p 动物/n 的/ude1 皮/n 、/wn 骨/ng 、/wn 筋腱/n 等/udeng 部位/n 熬/v 制/v 出来/vf 的/ude1 产物/n ，/wd 所以/c 如果/c 有/vyou 产品/n 中/f 含有/v 明胶/n ，/wd 它/rr 不/d 可能/v 是/vshi 纯/a 素/ag 的/ude1 ，/wd 因此/c 一些/mq 素食/n 主义/n 者/k 不/d 应当/v 选择/v 加入/v 明胶/n 的/ude1 产品/n 。/wj 

如今/t 有/vyou 一些/mq 全/a 素/ag 的/ude1 明胶/n 替代品/n 如/v 瓜/n 尔/Rg 豆/n 胶/n 、/wn 卡拉/nrf 胶/n 等/udeng ，/wd 还有/v 许多/m 纯/a 素/ag 的/ude1 物质/n 还有/v 和/cc 明胶/n 同样/b 的/ude1 成分/n ，/wd 如/v 纤维素/n 、/wn 琼脂/n 、/wn 瓜/n 尔/Rg 豆/n 胶/n 、/wn 黄/b 原/b 胶/n 、/wn 角/n 豆/n 果/ng 、/wn 果子/n 冻/v 等等/udeng ，/wd 所以/c 如果/c 你/rr 读/v 了/ule 成份/n 表/vg 看到/v 有/vyou 明胶/n ，/wd 那么/c 你/rr 可以/v 知道/v 那/rzv 不/d 是/vshi 纯/a 素/ag 的/ude1 ，/wd 但/c 如果/c 成份/n 表/n 中/f 有/vyou 以上/f 提到/v 的/ude1 纯/a 素/ag 的/ude1 物质/n ，/wd 即使/c 你/rr 是/vshi 纯/a 素/n 者/k ，/wd 你/rr 也/d 可以/v 吃/v 它/rr 了/y 。/wj  

39/m 健康/a 网/n 健康/ad 提示/v ：/wp 明胶/n 是/vshi 一/m 种/q 日常/b 常见/a 的/ude1 物质/n ，/wd 无需/v 对/p 它/rr 太/d 过/uguo 恐慌/an ，/wd 另外/c 需要/v 认识/v 的/ude1 是/vshi ，/wd 明胶/n 非/b 素食/n ，/wd 加入/v 了/ule 明胶/n 的/ude1 食品/n 也/d 非/b 素食/n ，/wd 但/c 有/vyou 一些/mq 纯/a 素/ag 的/ude1 明胶/n 替代品/n ，/wd 素食/n 主义/n 者/k 们/k 需要/v 特别/d 注意/v 。/wj 如果/c 网友/n 们/k 对于/p 明胶/n 仍然/d 不/d 放心/v ，/wd 那么/c 按照/p 范志红/nr 老师/n 的/ude1 建议/n ，/wd 就/d 只/d 能/v 不/d 购买/v 皮/n 冻/v 、/wn 肉冻/n 、/wn 水晶/n 肠/n 、/wn 灌/v 汤包/n 等/udeng 食品/n ，/wd 同时/c 少/ad 吃/v 各种/rz 软糖/n 、/wn 雪糕/n 、/wn 冰淇淋/n 等/udeng 产品/n 。/wj 特别/d 想/v 要/v 强调/v 的/ude1 是/vshi ，/wd 即使/c 当前/t 中国/ns 食品/n 安全/an 让/v 人/n 不/d 能/v 放心/v ，/wd 消费者/n 们/k 也/d 不/d 该/v 因为/p 恐慌/an 而/cc 因噎废食/vl ，/wd 远离/v 各种/rz 食品/n ，/wd 毕竟/d 民以食为天/nl ，/wd 掌握/v 更/d 多/a 的/ude1 健康/a 知识/n ，/wd 懂得/v 食物/n 挑选/v 技巧/n ，/wd 日常/b 生活/vn 注意/v 膳食/n 平衡/an 才/d 是/vshi 消费者/n 们/k 需要/v 花/n 更/d 多/a 心思/n 去/vf 关注/v 的/ude1 。/wj 

